### ISSUE TITLE
root level field can not have "sqlJoin"

### ISSUE THREAD

**Issue by tonyxiao** [join-monster/join-monster#103]
I'm getting the following error and I don't fully understand what it says. the same fields work fine when SQL monster is asked to handle the root node but complains and hits the following assertion when asked to only handle a subtree. 

https://github.com/stems/join-monster/blob/87379c871b917e8506fb27e018e90efa95ef7df2/src/util.js#L31

**Comment by dreamcodez** [comment]
The root node has nothing to join from, you must use a where here. Does that help?

**Comment by dreamcodez** [comment]
Can you paste the relevant code blocks for this root field resolver?  :)

**Comment by acarl005** [comment]
Closing this issue as it appears to have been a configuration error.
