### ISSUE TITLE
Can we add condition whether to do join or not

### ISSUE THREAD

**Issue by praseedasathaye** [join-monster/join-monster#104]
Here is how I am joining the tables
Expense (Parent Table)
        ExpenseCard (Child Table) (join expense and expenseCard)
                  CardDetails (Child of ExpenseCard Table) (join expenseCard and card)

Since the expenseCard is null for some of the records in the Expense, the second join fails with below error
```
{ TypeError: Cannot read property 'cardDetails' of null
    at /node_modules/join-monster/dist/batchPlanner.js:96:27
    at arrayMap (/node_modules/lodash/lodash.js:660:23)
```

Is there any way to add condition to not join if the parentTable field is null like below:

```
cardDetails: {
      type: Card,
     if (parentTable.Column is not null) {
      sqlJoin: (expenseCardTable, cardTable, args) => args.expenseSource=="Credit" ? `${expenseCardTable}.CARD_REFERENCE_ID = ${cardTable}.INSTRID` : ` `              
    }
    }
```

**Comment by acarl005** [comment]
What is the join-monster version? This may actually be a bug.

**Comment by acarl005** [comment]
This case should already be handled. We shouldn't have to explicitly condition on NOT NULL.

If its the bug I think it is, it has already been fixed in some versions. Try it again with the newest version, 1.2.1-beta.2

**Comment by praseedasathaye** [comment]
It worked with latest version. Thanks
