### ISSUE TITLE
GraphQLBoolean not mapped correctly

### ISSUE THREAD

**Issue by yngwi** [join-monster/join-monster#117]
Hi,
I'm building a small app to learn graphql with a MySQL backend. So far, everything works but I'm having a small problem with getting data from the database backend. I'm not sure if it is a problem with my code or with the library. I would be very glad if you could help me fix my problem.

Kind regards,
Daniel

Problem
---------

I have a type that includes a Boolean, declared as follows:
```javascript
is_verified: {
    type: GraphQLBoolean,
    description: 'Whether or not the user account was verified'
 }
```

The database column is declared in a knex migration like this:
```javascript
table.boolean('is_verified').notNullable().defaultTo(false);
```

When I create data with a mutation, the field entry is correctly set to `0` as MariaDB uses `TINYINT(1). ` internally to store Boolean values. When querying the data, it is seems to be correctly returned as `0`, I verified this by changing the type to `GraphQLInt`. As a Boolean, however, the returned value is `true`, not `false` as would have been correct. At least, that is what GraphiQL is displaying. Is that the expected behaviour?

Library versions
-----------------
join-monster: `1.2.1-beta.2`
knex: `0.12.9`
mariasql: `0.2.6`

**Comment by acarl005** [comment]
This seems to be an issue with graphql-js. Join Monster does not attempt to do any type conversion.   This is often done by the database driver and sometimes again by graphql execution. Join Monster correctly queried for this column. But the `GraphQLBoolean` type does not appear to be implicitly converting the integer to a boolean correctly. Although it's a little inconvenient, you could manually write a resolver to do the conversion.

```js
is_verified: {
    type: GraphQLBoolean,
    resolve: parentObj => parentObj.is_verified === 1,
    description: 'Whether or not the user account was verified'
}
```

**Comment by yngwi** [comment]
Thanks!
