### ISSUE TITLE
Directive support for SQL-JS links

### ISSUE THREAD

**Issue by migueloller** [join-monster/join-monster#12]
Is support for directives in future plans?

I created [`graphql-utilities`](https://github.com/bloveit/graphql-utilities) and all types and schema are driven using the schema language. It would be great if `join-monster` supported directives to define stuff like `sqlTable` and `uniqueKey`.

It could look something like this:

``` graphql
user @table("users") @pkey("id") {
  # ... selection set
}
```

**Comment by acarl005** [comment]
We would love to support the Schema Language. However, Join Monster sometimes requires you to add **functions**, like with `sqlJoin` and `where` conditions. In my understanding, this would not work well with directives.

We would love suggestions how to handle these. I suppose functions could be serialized as strings and placed in a directive, but that _could_ get messy.

**Comment by migueloller** [comment]
After thinking about it, the way to go would be to use the IDL for what it's meant to be used and then pass in all the Join Monster related stuff in the config just like resolvers are passed.

I'm working on releasing the fully featured version of the library soon and it should work with Join Monster out of the box.

**Comment by acarl005** [comment]
I agree. The extra info should go alongside the resolvers. I'm excited for this functionality. I'll be sure to add a section in the docs on usage with the IDL when I can.

**Comment by ozyman42** [comment]
Hey guys! Thanks for your work on this!
I was wondering where @migueloller is at with being able to support directives such as `@table('users')` or `@pkey("id")` in his `graphql-utilities` library, and if there is anything I can do in order to integrate that into the join-monster code base.

I'd really like to start using Join Monster with Apollo Server ASAP.

**Comment by migueloller** [comment]
@AlexLeung,

I've been super busy so work on https://github.com/bloveit/graphql-utilities/pull/12 has been a bit delayed. Pull requests are welcome! 😄 

Once that pull request comes in it won't have supports via directives but will work the same way the configuration works now.

Adding directive support would require `join-monster` to make changes so that it looks for these directives and can be done independently of `graphql-utilities`.

If you need any pointers let me know and I'll try to point you in the right direction.

**Comment by shockwavemoto** [comment]
We would love to support the Schema Language. However, Join Monster sometimes requires you to add functions, like with sqlJoin and where conditions. In my understanding, this would not work well with directives.
We would love suggestions how to handle these. I suppose functions could be serialized as strings and placed in a directive, but that could get messy.

I think i have a way to handle this kind of situation. I might send you a PR mght be in a day or two
:cheese: :smile:

**Comment by namnm** [comment]
Hi guys, any news? 😄

**Comment by namnm** [comment]
This is an implementation in PHP Laravel using directives, take a look at its idea, very cool:
https://lighthouse-php.netlify.com/

**Comment by EloB** [comment]
This might be interesting to implement https://github.com/taylorgoolsby/graphql-directive-connection

**Comment by nicoabie** [comment]
Closing till there is enough interest in adding this feature or creating a proposal
