### ISSUE TITLE
MSSQL and DB2 support SQL dialects

### ISSUE THREAD

**Issue by eucariop** [join-monster/join-monster#124]
It can support those SQL Dialects, but how?

**Comment by acarl005** [comment]
Ah yes, very possible! Supporting the full range of Join Monster features requires `LATERAL` or `CROSS/OUTER APPLY`, which are supported by DB2 and MSSQL respectively.

To do this, a module must be written for each dialect that implements certain vendor-specific cases, mostly around pagination. Maybe [this](https://github.com/stems/join-monster/tree/master/src/stringifiers) will help. Stem has no plans to implement these dialects, so a pull request will be happily accepted.

**Comment by eucariop** [comment]
Ok, thank.

**Comment by khell** [comment]
I'm working on mssql support here: https://github.com/khell/join-monster/commits/mssql

Please feel free to contribute :) So far it's working for everything we need it for, but I still need tests written and any other behaviours we haven't encountered identified.

**Comment by jnreynoso** [comment]
w8 for this :heart:

**Comment by khell** [comment]
There's no need to wait; it can be used now if you build it yourself. I haven't had time to prepare tests or clean it up so it can be submitted as a PR yet is all.
