### ISSUE TITLE
uniqueKey null

### ISSUE THREAD

**Issue by xserosm** [join-monster/join-monster#125]
Hi,

I have a table with unique index which also could be null (column g_id)
```
g_id | count
-----+------+
   3 |   10 |
   2 |   20 |
   1 |   20 |
     |   50 |
```
`uniqueKey` is set to `'g_id'` in GraphQL schema.
When I want to get a row with empty g_id (`WHERE g_id IS NULL`) I get null result
According to debug logs the row is selected from db, but not pushed to response. No problems with another rows.

Could you explain this behavior please?

"version": "1.2.1-beta.9"

**Comment by acarl005** [comment]
Can you run your app with this environment variable: `DEBUG=join-monster`, trigger this scenario again, and post the additional output?

**Comment by xserosm** [comment]
SCHEMA
```javascript
const StatisticTotal = new GraphQLObjectType({
	description: 'Total statistic',
	name: 'StatisticTotal',
	sqlTable: 'statistics_total',
	uniqueKey: ['game_id'],
	fields: () => ({
		id: {
			type: new GraphQLNonNull(GraphQLID),
			sqlDeps: ['game_id'],
			resolve(stat) {
				return stat.game_id ? stat.game_id : 0
			}
		},
		matchesCount: {
			type: new GraphQLNonNull(GraphQLInt),
			sqlColumn: 'matches'
		}
	})
})
```

QUERY
```javascript
statisticTotal: {
	description: 'A total statistic',
	type: StatisticTotal,
	args: {
		gameID: { type: GraphQLID }
	},

	where: (statTable, { gameID }) => {
		if (gameID) {
			return `${statTable}.game_id = ${+gameID}`
		}

		return `${statTable}.game_id IS NULL`
	},

	resolve: (parent, args, context, resolveInfo) =>
		joinMonster(resolveInfo, context, sql =>
			postgres.query(sql)
		, config.psql.joinMonster)
}
```
REQUEST
```
{
  statisticTotal{
    id
    matchesCount
  }
}
```

RESPONSE
```javascript
{
  "data": {
    "statisticTotal": null
  }
}
```

LOGS
```
  join-monster SQL_AST
  join-monster  { type: 'table',
  name: 'statistics_total',
  as: 'statisticT',
  children:
   [ { type: 'composite',
       name: [ 'game_id' ],
       fieldName: 'gam',
       as: 'gam' },
     { type: 'column',
       name: 'matches',
       fieldName: 'matchesCount',
       as: 'matches' },
     { type: 'columnDeps', names: { game_id: 'game_id' } } ],
  fieldName: 'statisticTotal',
  grabMany: false,
  where: [Function: where] } +0ms
  join-monster
  join-monster SQL
  join-monster  SELECT
  NULLIF(CONCAT("statisticT"."game_id"), '') AS "gam",
  "statisticT"."matches" AS "matches",
  "statisticT"."game_id" AS "game_id"
FROM statistics_total "statisticT"
WHERE "statisticT".game_id IS NULL +5ms
  join-monster
  join-monster SHAPE_DEFINITION
  join-monster  { gam: 'gam', matchesCount: 'matches', game_id: 'game_id' } +1ms
  join-monster
  join-monster RAW DATA
  join-monster  [ anonymous { gam: null, matches: 0, game_id: null } ] +261ms
  join-monster 1 rows... +0ms
```

**Comment by acarl005** [comment]
I'm afraid this is not supported. Columns with unique *indexes* do not suffice as keys if they are nullable because they cannot uniquely identify each row. The ability to identify each entity by its key is vital for the shaping process, as each entity may appear in multiple rows after a `JOIN`. Join Monster needs to be able to distinguish between one entity appearing in multiple rows and many entities with the same values in many rows.

It has to be a unique *key*. It is analogous to a primary key, but the reason I didn't use the term `primaryKey` is that Join Monster doesn't need **thee* primary key, just a column (or combination of columns) that can identify each row. 

Since you're using Postgres, maybe you could use the row oid?

**Comment by xserosm** [comment]
Currently I created additional column with default 0 and added it to uniqueKey. It is works since there are no duplicate rows on game_id(including NULL).
But thanks for referencing to row  oid, will think about to use it.
