### ISSUE TITLE
Problem with alias length

### ISSUE THREAD

**Issue by sywka** [join-monster/join-monster#129]
Aliases for fields grow to huge sizes with large nesting of objects, for example:
`"contact$"."NAME" AS "claims__shop__company__contact$__name"`
This makes the query more understandable, however, in the database that we use (firebird), there is a limit on the length of the names in 31 characters.

Can it be possible to replace compound alphabetic aliases with numeric identifiers of limited length?

Update 

I didn't notice the minify option in the documentation, sorry

**Comment by Akiwaga** [comment]
Could you tell me how did you resolve this issue and used the minify. I tried to use minify and couldnt get successful. return joinMonster(resolveInfo, context, sql => db.run(sql), [minify:true]).

Update: - It is working now.

**Comment by Akiwaga** [comment]
Nevermind, I got that working. !!
