### ISSUE TITLE
nest expects param data to be in the form of a plain object or an array of plain objects (forming a table)

### ISSUE THREAD

**Issue by josercarmo** [join-monster/join-monster#13]
So, I'm in trouble on the return knex.raw, what am I doing wrong?, always returns the error below...
My knex is ok, and return the data...Thanks, this software help me a lot!!!! 

``` javascript
const CursoType = new GraphQLObjectType({
  name: 'Curso',
  sqlTable: 'curso',
  uniqueKey: 'id',
  description: 'Isto representa um curso',
  fields: () => ({
    id: {
      type: GraphQLInt
    },
    name: {
      type: GraphQLString
    }
  })
})

RootQuery ...
cursos: {
      description: 'Isto representa um curso',
      type: new GraphQLList(CursoType),
      resolve: (parent, args, context, ast) => {
        return joinMonster(ast, context, sql => {
          return knex.raw(sql)
        })
      }
    }
```

``` json
{
  "data": {
    "academic": {
      "cursos": null
    }
  },
  "errors": [
    {
      "message": "nest expects param data to be in the form of a plain object or an array of plain objects (forming a table)",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    }
  ]
}
```

**Comment by acarl005** [comment]
Which dialect are you using with knex? Also, which version of knex? I believe `knex.raw` returns a slightly different shape of object depending on the dialect. This will work with SQLite, but not, for example with postgres. With postgres you need to grab the `rows` property on that object, like so:
```javascript
resolve: (parent, args, context, ast) => {
    return joinMonster(ast, context, sql => {
        return knex.raw(sql).then(data => data.rows)
    })
}
```
If that doesn't work, can you `console.log` whatever `data` is so we can see what that object looks like?

**Comment by acarl005** [comment]
@joserochadocarmo 
Which dialect are you using with knex? Also, which version of knex? I believe `knex.raw` returns a slightly different shape of object depending on the dialect. This will work with SQLite, but not, for example with postgres. With postgres you need to grab the `rows` property on that object, like so:

``` javascript
resolve: (parent, args, context, ast) => {
    return joinMonster(ast, context, sql => {
        return knex.raw(sql).then(data => data.rows)
    })
}
```

If that doesn't work, can you `console.log` whatever `data` is so we can see what that object looks like?

**Comment by josercarmo** [comment]
Thanks @acarl005, It worked!!! I'm work with postgres and you were right about grab the rows.

**Comment by acarl005** [comment]
Yeah this wasn't super clear in the docs. I made an update that gives a clearer error message.
