### ISSUE TITLE
Search feature in docs is broken

### ISSUE THREAD

**Issue by Reggino** [join-monster/join-monster#130]
Thanks for this, this is awesome.

However, when using the documentation on [http://join-monster.readthedocs.io/en/latest/](http://join-monster.readthedocs.io/en/latest/) i can't find anything using the search function. Whatever i search, there never seems to be a result?

**Comment by acarl005** [comment]
This has been an open issue in readthedocs for almost two years: rtfd/readthedocs.org#1487. It looks like a workaround has been found (rtfd/readthedocs.org#1088). I'll try to implement this in due time but I am actively working on a major release so I won't prioritize this. PR will be gladly accepted!

**Comment by nicoabie** [comment]
Mkdocs were update to latest stable version and this is fixed now see https://join-monster.readthedocs.io/en/latest/search.html?q=thunked
