### ISSUE TITLE
Relay mutations

### ISSUE THREAD

**Issue by yngwi** [join-monster/join-monster#131]
Hi,
are there any informations on how to implement [Relay-compatible mutations](https://facebook.github.io/relay/docs/graphql-mutations.html)? I tried using the helper method from `graphql-relay`, similar to the queries, but I didn't have success yet.

This is what I have so far:

```javascript
    merge: () => mutationWithClientMutationId({
        name: 'mergeActivity',
        inputFields: {
            name: {
                type: new GraphQLNonNull(GraphQLString),
                description: 'The activity name'
            },
            tagName: {
                type: GraphQLString,
                description: 'The name of a tag to connect to; it will be created if it is not yet existing; set to to an empty string to delete any tag association'
            }
        },
        outputFields: {
            activity: {
                type: ActivityType,
                where: (activitiesTable, args, context) => `${activitiesTable}.id = ${context.id}`,
                resolve: ({args, context, resolveInfo}) => ActivityResolver.merge(args, context, resolveInfo)
            }
        },
        mutateAndGetPayload: (args, context, resolveInfo) => ({args, context, resolveInfo})
    }),
```

I tried different combinations of `outputFields` and `mutateAndGetPayload`, some where the second function does the actual mutation and resolve, and the version above, where I tried to do everything in the outputFields. This version is the one with the most success. My resolver mutates and returns the resulting object so I figured this might be the correct way to do it. I just added the where clause because I also used it on the version of the mutation without Relay where everything worked fine. I don't think it does anything here...

When executing this mutation in GraphiQL, I get the following error message:
`Must call joinMonster in a resolver on a field where the type is decorated with "sqlTable".`

Is there a code example on how to do this correctly? I figure as this is an integral part of Relay and join-monster claims to `work[...] well with graphql-relay-js` this is not something that I am the first to try?

I'm sorry if I ask something obvious and thank you for all your help!

Daniel

PS.: I'm using
```
    "graphql": "^0.9.3",
    "graphql-relay": "^0.5.1",
    "join-monster": "^1.2.4-beta.1",
```

**Comment by kirgene** [comment]
I have the same question.
If someone provide code snippet of how to use join-monster with relay mutations properly it would be great.

**Comment by Felix-N** [comment]
My understanding currently is, to use the joinmonster context to pass the payload from the resolve function into the where function to limit the result

**Comment by theogravity** [comment]
`mutationWithClientMutationId` is creating the intermediate type on `mergeActivity` called `mergeActivityPayload` using the `outputFields` data, which looks like this:

```js
const mergeActivityPayloadType = new GraphQLObjectType({
  name: 'mergeActivityPayload',
  fields: {
    activity: {
      type: ActivityType,
      where: (activitiesTable, args, context) => `${activitiesTable}.id = ${context.id}`,
      resolve: (args, context, resolveInfo) => ActivityResolver.merge(args, context, resolveInfo)
    }
  }
})
```

Implemented as:

```graphql
RootMutation {
   merge (input: mergeActivityInput): mergeActivityPayload
}
```

The OP is getting the `Must call joinMonster in a resolver on a field where the type is decorated with "sqlTable".` error because `mergeActivityPayload` lacks a `sqlTable`. 

Another problem with this is `sqlTable` is not necessary for the `mergeActivityPayload` - the logic to fetch the individual result fields are contained already within them and their associated type.

If joinMonster had a flag or something to ignore the `sqlTable` requirement on a mutation's payload type, it would help.

I've tried using the `jmIgnoreAll` / `jmIgnoreTable` on the payload type in my own impl without success.

Related: https://github.com/stems/join-monster-demo/issues/5

**Comment by theogravity** [comment]
Ok, figured it out.  The trick is to not populate your output data in any way. This causes the graphQL framework to go directly to that type's resolver instead to do the lookup for that data.

- In the `merge` resolver, you want to just return an object with your data to later feed into your payload fields. 
- In the `outputFields` field def, you want to define your `where` and `resolve`.
- When `resolve (resolverRslt)`, is called, `resolverRslt` will have the data from step 1. Call `joinMonster` and feed in your `resolverRslt` into the `context`
- Next, the `where` def will be called. The third parameter will contain the `context` you fed in step 3. Use this to filter out the specific item you need.

That's it!

Try this:

```js
    merge: () => mutationWithClientMutationId({
        name: 'mergeActivity',
        inputFields: {
            name: {
                type: new GraphQLNonNull(GraphQLString),
                description: 'The activity name'
            },
            tagName: {
                type: GraphQLString,
                description: 'The name of a tag to connect to; it will be created if it is not yet existing; set to to an empty string to delete any tag association'
            }
        },
        outputFields: {
            activity: {
                type: ActivityType,
                where: (activitiesTable, args, context) => {
                   // be aware of any potential sql injection issues - the following is not sanitized input
                   return `${activitiesTable}.id = '${context.id}'`
                },
                resolve: (resolverRslt, args, context, resolveInfo) => {
                   return joinMonster(resolveInfo, { id: resolverRslt.__tagId } , (sql) => knex.raw(sql),  { dialect: 'pg' })
                }
            }
        },
        mutateAndGetPayload: (root, args, context, resolveInfo) => {
             // your insert to database code should go here

             // you'll prob have an id from the database call, fill it out below
            // do not return any of the outputFields that you want fetched
             return {
                // going to assume the name is the id here
                 __tagId: args.input.name // replace with db id result
             }
        }
    }),
```

If you're not using `mutationWithClientMutationId`, then it might look like this:

```js
const mergeActivityPayloadType = new GraphQLObjectType({
  name: 'mergeActivityPayload',
  fields: {
    activity: {
      type: ActivityType,
       where: (activitiesTable, args, context) => {
          // be aware of any potential sql injection issues - the following is not sanitized input
         return `${activitiesTable}.id = '${context.id}'`
       },
       resolve: (resolverRslt, args, context, resolveInfo) => {
         return joinMonster(resolveInfo, { id: resolverRslt.__tagId } , (sql) => knex.raw(sql),  { dialect: 'pg' })
       }
    }
  }
})

const RootMutation = new GraphQLObjectType({
  name: 'RootMutation',
  fields: {
    merge: {
      type: mergeActivityPayloadType,
      args: {
        input: {
           // this needs to be defined, but not related to this problem
           type: mergeActivityInput
        }
      }
      resolve: (root, args) {
             // your insert to database code should go here

             // you'll prob have an id from the database call, fill it out below
            // do not return any of the outputFields that you want fetched
             return {
                // going to assume the name is the id here
                 __tagId: args.input.name // replace with db id result
             }
      }
    }
  }
}
```

**Comment by renato** [comment]
I got it working based on @sangheestyle's commit that referenced this issue. Is there any alternative (or a plan for one) that does not depend on a new "...Payload" type for every mutation? Thanks.

**Comment by sangheestyle** [comment]
@renato Did you find any other way?

**Comment by konsumer** [comment]
@theogravity 's solution helped me come to a  solution I like for when I'm using graphql-tools (so I can define my graphql all in SDL and merge all my resolvers & sql-monster stuff.)

[Here](https://github.com/konsumer/join-monster-demo) is a demo repo that uses sql-monster & graphql-tools.

This has greatly simplified my model/resolver management, as I just worry about the database lookups in one place. It looks like it might be a bit complicated for just one resolver, but once you start making a bunch of resolvers & types, it really makes things simpler.

I implemented a `schemaDirective` called `@sql` that can inject join-monster stuff into models, in a generic way:

```grahql
type Query {
  things: [Thing]! @sql
  thing(id: ID!): Thing! @sql
}

type Mutation {
  createThing(input: ThingCreate): Thing! @sql
  updateThing(input: ThingUpdate): Thing! @sql
  deleteThing(id: ID!): Thing! @sql
}

type Thing @sql {
  id: ID! 
  title: String!
}

input ThingUpdate {
  id: ID!
  title: String
}

input ThingCreate {
  title: String!
}
```
and my resolvers just return `{ id }`:

```js
export default {
  Query: {
    thing: (parent, args) => args,
    things: (parent, args) => args
  },

  Mutation: {
    createThing: async (parent, { input }, ctx, resolveInfo) => {
      const [id] = await ctx.knex('things').insert(input)
      return { id }
    },

    updateThing: async (parent, { input: { id, ...updates } }, ctx, resolveInfo) => {
      await ctx.knex('things').where({ id }).update(updates)
      return { id }
    },

    deleteThing: async (parent, { id }, ctx, resolveInfo) => {
      const _filled = await sqlResolver(parent, { id }, ctx, resolveInfo)
      await await ctx.knex('things').where({ id }).del()
      // there will not be a record after this, so I look it up first and return it with _filled
      return { _filled }
    }
  }
}
```

I used `_filled` to return a record that I lookup before deletion, so join-monster knows to not do a search (but other child resolvers can.)
