### ISSUE TITLE
inconsistent behaviour with query enums in where function

### ISSUE THREAD

**Issue by bradzacher** [join-monster/join-monster#139]
If you pass an enum value directly in a query:
```
query {
   Obj(enum_p:val) { ... }
}
```
Then join monster will pass the enum's literal string to the `where` function (i.e. `args.enum_p === 'val'`)

However if you pass an enum value via a variable:
```
enum EnumP {
   val: 2
}

query ($enum_p:EnumP) {
    Obj(enum_p:$enum_p) { ... }
}

variables: {
    $enum_p: 'val'
}
```
Then join monster will pass the enum's defined value to the where function (i.e. `args.enum_p === 2`)

I assume that this is because when you pass a variable, graphql automatically resolves the value for you?

**Comment by acarl005** [comment]
This is a bug. I missed this during the argument parsing. I'll fix this shortly. Join Monster re-implemented the argument parsing function rather than relying on the one in graphql-js.

**Comment by Reggino** [comment]
I had similar issues where an array (GraphQLList) nested in an object would be parsed as `undefined`. My workaround was this change: https://github.com/Reggino/join-monster/commit/bef7cb0aa646b1f9e87a18dfb95dfdb35432f0e3

**Comment by acarl005** [comment]
This should now be fixed.
