### ISSUE TITLE
Propagation of arguments to all fields transitivelly

### ISSUE THREAD

**Issue by marazt** [join-monster/join-monster#140]
Hi, maybe I'm doing something wrong, but I have a following issue:

I have a query with arguments, let say 

```javascript
{
  a (dateFrom, dateTo) {
    b {
      c {...}
    }
  }
}
```

And I'm using SQL Db together with MongoDb to get aggregate these data. 

```typescript
const A: GraphQLObjectType = new GraphQLObjectType({
  name: 'A',
  sqlTable: 'public."a"',
  uniqueKey: 'id',
  fields: () => ({
    id: {
      description: 'A id',
      type: new GraphQLNonNull(GraphQLID)
    },
    b: {
      description: 'b',
      type: B,
      sqlBatch: {
        thisKey: 'id',
        parentKey: 'id'
      }
    }
  })
})
```

```typescript
const B: GraphQLObjectType = new GraphQLObjectType({
  name: 'B',
  sqlTable: 'public."b"',
  uniqueKey: 'id',
  fields: () => ({
    id: {
      description: 'B id',
      type: new GraphQLNonNull(GraphQLID)
    },
    c: {
      description: 'C',
      type: C,
      jmIgnoreTable: true,
      resolve: async (parent, args, context, resolveInfo) => {
       // I need to access args set in a query using A as a type here to query MongoDb with parameters
       return {...}
     }
    }
})
```

Even the data that will use args is on type C, I need to set it on type A. I tried to set args to context to propagate it down, i.e.:

```typescript
      resolve: (_parent, args, _context, resolveInfo) => {
        return joinMonster(resolveInfo, {args}, sql => {
          return knex.raw(sql).then((res) => {
            return res
          })
        })
      }
```
But it seems that thanks **jmIgnoreTable** parameter on **C** the propagation is stopped.

EDIT:
It seems it not a join-monster issue, but graphql-js one:
* https://github.com/graphql/graphql-js/issues/19
* https://github.com/graphql-go/graphql/issues/125

So in case of resolve, it must be accessed via the fourth parameter **ast**

**Comment by acarl005** [comment]
This is an inherent limitation of graphql-js. Resolvers only see the args of the current field. Otherwise you have to dig around that fourth parameter `resolveInfo`. Closing this issue since it is not relevant to join-monster. You can re-open if there is an idea for how join-monster might address this.
