### ISSUE TITLE
tables aliases

### ISSUE THREAD

**Issue by MichelWilleput** [join-monster/join-monster#147]
Hello, 
I want to build a custom where clause with fields of joined tables and not only the main table of the query.
Because join monster created aliases on the tables in the resolve function, the aliases are not known yet when the where clause is built.
I was wondering if there a way I could achieve this or is there a way to tell join monster not to created the aliases ?
Thank yo very much

**Comment by acarl005** [comment]
You can add a `where` function on any field which has an object type mapped to a SQL table. Each function receives its respective alias as the first parameter.

[API docs](http://join-monster.readthedocs.io/en/latest/API/#where)

**Comment by MichelWilleput** [comment]
Hi,
I already had a where clause in the query. Added also where clauses in the GraphObjects
Thank you for your quick reply.
