### ISSUE TITLE
Does join-monster supports polymorphic relationships?

### ISSUE THREAD

**Issue by s-panferov** [join-monster/join-monster#150]
Hello, thanks for the amazing library. I used join-monster in my project with no troubles, but now I faced with a problem that I need some kind of polymorphic relationship.

I'm trying to use ["Exclusive Belongings To" strategy](https://hashrocket.com/blog/posts/modeling-polymorphic-associations-in-a-relational-database#exclusive-belongs-to-aka-exclusive-arc-) but it seems that join-monster doesn't support this kind of relationships.

As I understand, it could be implemented somehow with `batch` fetching, but it requires to understand union graphql types.

Details:

My database structure:

```
teams (id, name)
users (id, name)
team_members (
  owner_id references teams (id),
  team_id references teams (id),
  user_id references users (id)
)
```

I want to fetch all team members (member can be either a team or a user)

---

The workaround is to define several fields in my schema. Instead of just `members` I have to create separate `teams` and `users` fields.

**Comment by acarl005** [comment]
This is technically possible, although not easy. Both options will preclude the use of `sqlBatch`, as that requires that the foreign key be a fixed column. So you'll have to do a 'sqlJoin`. You have two options:

1. Use a `GraphQLUnionType` to union the teams and users. This will let you treat them as polymorphic in the API as well.
2. Or, if you're okay with making the two a single type in GraphQL, create a `GraphQLObjectType` where the `sqlTable` is a view combining the two tables together.
