### ISSUE TITLE
Perfomace subquery

### ISSUE THREAD

**Issue by josercarmo** [join-monster/join-monster#153]
So, do not you think that this generated sql decreases performace? The good thing of join-monster is that sql only returns what you requested, but in that subquery has a "table. *"

```sql
SELECT
  "users"."id" AS "id",
  "users"."email_address" AS "email",
  "posts"."id" AS "posts__id",
  "posts"."body" AS "posts__body"
FROM (
  SELECT "users".*, count(*) OVER () AS "$total"
  FROM accounts "users"
  WHERE TRUE
  ORDER BY "users"."id" ASC
  LIMIT 12 OFFSET 0
) "users"
LEFT JOIN posts "posts" ON "users".id = "posts".author_id
ORDER BY "users"."id" ASC, "posts"."id" ASC
```
Should it be so?
```sql
SELECT
  "users"."id" AS "id",
  "users"."email_address" AS "email",
  "posts"."id" AS "posts__id",
  "posts"."body" AS "posts__body"
FROM (
  SELECT "users"."id" AS "id",
  "users"."email_address" AS "email", count(*) OVER () AS "$total"
  FROM accounts "users"
  WHERE TRUE
  ORDER BY "users"."id" ASC
  LIMIT 12 OFFSET 0
) "users"
LEFT JOIN posts "posts" ON "users".id = "posts".author_id
ORDER BY "users"."id" ASC, "posts"."id" ASC
```

**Comment by acarl005** [comment]
The *outer query* only selects the column actually needed, so the extra columns won't get sent over the wire. There are, however, problems that can arise by omitting columns from the *subquery*. Its possible that some of those columns might be referred to in a `WHERE` clause in the outer query. So we need to keep all the columns for the outer query.

If a benchmark is posted that shows adverse effects on performance, we will consider optimizing this further.

**Comment by josercarmo** [comment]
Oh, you right, I had forgotten the part of the clause where. thanks for explain so fast.
