### ISSUE TITLE
For many-to-many junctions, support fields from the junction table to the edge

### ISSUE THREAD

**Issue by bw** [join-monster/join-monster#155]
**I'd like to propose that join-monster support fields from the junction table of a many-to-many join to a Relay-compliant edge.** This is a follow-up from [my comment on #36](https://github.com/stems/join-monster/issues/36#issuecomment-313540630).

----

To follow up on issue #36: join-monster v2 recently added support for these junction table fields (thanks!), but they are only surfaced on the child node and not the edge. This is not ideal for a number of reasons--

### Will break schematic correctness

First and foremost, this isn't a schematically "correct" way of surfacing fields from an edge. Putting fields on something that it is not from can create a variety of problems, but from a high-level perspective it hurts a lot of the cleanliness, simplicity, and durability of the GraphQL protocol.

### Can break caching or use cases that assume the durability of nodes

Second, this can cause problems with caching frameworks that assume the durability of nodes. For example, Relay looks at and uses the "global ID" to aggressively cache GraphQL nodes. This means that it will cache (and incorrectly reuse) these fields because it thinks that they belong to the node, not the edge.

For us, this is a hypothetical-- we personally don't use Relay or this kind of aggressive caching, but I think it's definitely possible to create problems later on if we do.

### Can force the creation of a large number of unnecessary fields

Third, if you have nodes with many different _types_ of edges (we do), then placing edge fields on the node becomes very unwieldy very quickly. If we have `AppleBananaEdge` with fields A, B, C, and D; and `CornBananaEdge` with fields E, F, G, H; and both point to `Banana`, then `Banana` will now need to have eight additional fields. 

In our testing, we tried to prefix these edge fields with `edge_` (for example, `edge_A`, `edge_B`, ... , `edge_H`) but eight more fields is eight more fields. This problem is especially exasperated because it's not immediately obvious which edge fields belong to-- with `CornBananaEdge`, which `edge_` fields are we allowed to query again? 

So maybe the next workaround is to prefix with the full edge name (`CornEdge_` or `CornBananaEdge_`)... you can see how this gets very annoying very quickly. 

Plus, there is additional server-side logic needed: we need to be checking in the resolvers for these fields to make sure that the data is valid for the _edge_ used.

----

In our specific use case we don't actually use Relay, but we've tried to build Relay-compliant servers because the way that it handles pagination, connections/edges, etc. is smart and battle-tested.

I do understand that `graphql-relay-js`, which is the current best method of structuring Relay-compliant many-to-many joins, is a bit limited when it comes to this. The [connectionDefinitions](https://github.com/graphql/graphql-relay-js/blob/master/src/connection/connection.js#L84) are fairly flexible, but [connectionFromArray](https://github.com/graphql/graphql-relay-js/blob/master/src/connection/arrayconnection.js) is not great for this use case since it really needs to have its incoming data as an array.

So to do this-- and I'm now thinking in terms of join-monster implementing this, admittedly without full understanding of join-monster mechanics-- we might need to write our own resolving helper? 

Such that, for a hypothetical connection/edge from Apple to Banana, instead of writing

```js
// A generic BananaConnection defined earlier
export const BananaConnection = connectionDefinitions(connectionConfig).connectionType;

...

// To resolve the field on Apple
type: BananaConnection,
resolve: (node, args) => connectionFromArray(node.bananaConnection, args),
```

we will instead (a) define specialized connections that support the particular edge; and (b) use those definitions, wrapped with a join-monster many-to-many connection helper:

```js
// Define both generic and specific connections to Banana earlier
export const BananaConnection = connectionDefinitions(...).connectionType;
export const AppleBananaConnection = connectionDefinitions(...).connectionType;

...

// And have a custom resolver
type: AppleBananaConnection,
resolve: (node, args) => connectionFromJoinMonsterManyToMany(node.bananaConnection, args),
```

This is just a thought. I'd love to help however I can in making this happen. And thanks again!

**Comment by bw** [comment]
@acarl005 just checking in on this! I was thinking that a simplified solution might be to allow us to specify if we always want to grab a field from the `junction.include` statement:

```js
include: {
  closenessScore: {
    sqlColumn: 'closeness',
    includeAlways: true, // Add this
  },
},
```

That way, we would be able to grab it from the edge fields:

```js
export const ContactsConnection = connectionDefinitions({
  nodeType: Contact,
  connectionFields: { ... },
  edgeFields: {
    closenessScore: {
      type: GraphQLInt,
      resolve: ({ node }) => node.closenessScore,
    },
  },
}).connectionType;
```

**Comment by bw** [comment]
For anyone else stumbling across this issue or trying to get junction fields on a Relay-compliant edge, I've written [a temporary hack](https://gist.github.com/bw/4444c7866742ebfb499294c5da5b1ee9) to let you achieve this. It requires that a dummy field on the node itself be requested each time.

**Comment by nicoabie** [comment]
I believe this should be fixed using https://join-monster.readthedocs.io/en/latest/many-to-many/#including-data-from-the-junction with alwaysFetch https://join-monster.readthedocs.io/en/latest/misc/
