### ISSUE TITLE
Bug junction join with non-unique results

### ISSUE THREAD

**Issue by bradzacher** [join-monster/join-monster#156]
I'm doing a junction join which ultimately returns non-unique results for the final join.
Join monster doesn't seem to be able to handle this and returns nothing for the query:

gql query:
```graphql
query {
    Entity1(id:1) {
        id,
        related_entity3s {
            id
        }
    }
}
```
generated sql:
```sql
SELECT
  `Entity1`.`id` AS `id`,
  `Entity3`.`id` AS `Entity3__id`
FROM Entity1 `Entity1`
LEFT JOIN Entity2 `Entity2` ON `Entity1`.id = `Entity2`.entity1_id
LEFT JOIN Entity3 `Entity3` ON `Entity2`.field2 = `Entity3`.field2
WHERE `Entity1`.`id` = 1
```
SQL results:
```
| id | Entity3__id |
| -- | ----------- |
| 1  | 2           |
| 1  | 2           |
| 1  | 2           |
```
GQL result:
```JSON
{
    "data": {
        "Entity1": []
    }
}
```

**Comment by acarl005** [comment]
Can you run it again with the environment variable `DEBUG=join-monster` and post the additional output?

**Comment by acarl005** [comment]
@bradzacher Also what did you indicate as the `uniqueKey`s for each type?

**Comment by bradzacher** [comment]
I reworked my code around this, and it works fine now.
I believe this was a configuration error with the join.
