### ISSUE TITLE
TypeError: Cannot read property 'length' of null.

### ISSUE THREAD

**Issue by marazt** [join-monster/join-monster#158]
This error occurs in method util.maybeQuote (value.length) while entity **A** has a foreign key to entity **B** and is joining **B** via **sqlBatch**. When **A.b_id** is null, a null value is passed into maybeQuote method and fails.

I have created a pull request with fix #157

**Comment by marazt** [comment]
It can be merged (pull request is merged) :)

**Comment by acarl005** [comment]
PR was merged 👍
