### ISSUE TITLE
Doesn't work with Apollo Optics

### ISSUE THREAD

**Issue by wmdmark** [join-monster/join-monster#164]
I'm not sure if this should be reported in the optics repo or here. Feel free to close if this isn't a `join-monster` problem.

From what I can tell, the issues is that [Apollo optics](http://www.apollodata.com/optics/) tries to add [default resolve functions to the schema](https://github.com/apollographql/optics-agent-js/blob/master/src/Instrument.js#L248-L251) if none are present on a filed which ends up overriding Join Monster's default resolver. 

Again, not really sure if this is an actual problem with Join Monster or Optics but I'd love to be able to use optics and Join Monster together.

**Comment by acarl005** [comment]
It works, you just have to explicitly add `sqlColumn` to any field that assumed same-name columns.

**Comment by acarl005** [comment]
Updated the [docs](http://join-monster.readthedocs.io/en/latest/field-metadata/)
