### ISSUE TITLE
Docs for Express MySQL Dialect?

### ISSUE THREAD

**Issue by MichelDiz** [join-monster/join-monster#165]
Some example or documentation available?

Which arguments to use? To log in to the local MySql server? Is it the same as the Sequelize? I met JM a few hours ago, but I did not get anything by example. I'll start testing soon.

Thank you. Best regards.

**Comment by acarl005** [comment]
All the necessary documentation is [here](http://join-monster.readthedocs.io/en/latest/).

You can find an example API [here](https://github.com/stems/join-monster-demo). Although this example uses postgres, the only thing that has to change is the postgres-specific parts.

To find out how to connect to MySQL is not under the purview of join-monster, and hence does not belong in join-monster's docs or issues. You should consult the docs for whichever MySQL driver or ORM you decide to use.

**Comment by MichelDiz** [comment]
Hi,
Thank you. I was already digging this example. But it uses "KOA", my project is Express and it was using Sequelize. But I've already been able to configure Knex to work with Mysql (and with Express).

Thanks one more time! Best regards.
