### ISSUE TITLE
Unit testing of resolvers

### ISSUE THREAD

**Issue by mydnicq** [join-monster/join-monster#175]
If I want to unit test resolvers, I found it impossible to do so, because joinmonster relies on 'resolveInfo' argument which is only available during query execution. 

Here is an example of a simple resolver which utilizes joinMonster to relieve my question:

```js
user (obj, args, ctx, resolveInfo) {
  return joinMonster(resolveInfo, {}, sql => {
    return ctx.db.run(sql)
  })
}
```

The question is, what would be the appropriate way to unit test resolvers? Is it possible to somehow mock the resolveInfo argument?

If resolver unit testing is not doable in a way that I'm approaching, what would be the alternative? 
I'm thinking about this option:

```js
const query = `
  query User {
    user {
        name
    }
  }
`;

const rootValue = {};
const context = getContext();

const result = await graphql(schema, query, rootValue, context);
const { data } = result;

// and the assertions follow
```

**Comment by acarl005** [comment]
This is an interesting topic. Our team doesn't yet have a definite solution.

What we ended up doing is redefining a "unit". Instead of testing the resolver functions as units, we test *fields* as units. It's precisely the approach you have in your example.

Alternatively, you can try to import some [internal functions](https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L694) from the `graphql` module to create the `resolveInfo`:

```js
import { buildResolveInfo } from 'graphql/execution/execute'
```

If someone has this set-up figured out, posting any boilerplate code here would be appreciated!

**Comment by mydnicq** [comment]
I made a quick plunge into the [internal functions](https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L694) from the 'graphql' module and I think we could use some functions to mock the 'resolveInfo'. But wouldn't this be just another (more complicated) way for testing _fields_ as units as you had mentioned? 

If I somehow mock the `resolveInfo` I will have to build the `ExecutionContext` 'manually', which is already built for me when I run test in this way:

```
const query = `
  query User {
    user {
        name
    }
  }
`;
const rootValue = {};
const context = getContext();
const result = await graphql(schema, query, rootValue, context);
```
I think that when you redefining a "unit" and test fields as units, you're much closer to so called integration tests, where you test several modules at once: the consistency of graphql schema, the context and finally the execution / resolvers. Is this the right way for testing graphQL APIs? As many things in software development, this might be a question of a personal view about API testing.

**Comment by acarl005** [comment]
Yeah the definition of a **unit** is left up to personal discretion. I would argue that its reasonable to consider one `GraphQLObjectType` a unit, or perhaps its fields are units. This is analogous to how either *classes* or their *methods* could be the units in OOP. You can set up test GraphQLSchemas with only the object type you are interested in testing.

Sure, your tests would be running "other modules", like GraphQL's execution engine, but you don't have to run other modules of your source code (assuming things are mocked). It's not like you're actually *testing* `graphql` itself. I could say that when you test a JS function in Node.js, you're running modules of code within the V8 engine and libuv, but that's not actually being tested. Analogously, to plug your object types into graphql's execution modules does not violate the spirit of unit testing in my opinion.

**Comment by mydnicq** [comment]
@acarl005 You've written some excellent findings, which helped me to think about GraphQL API testing in a different way. Thx!
