### ISSUE TITLE
Use with multiple databases?

### ISSUE THREAD

**Issue by johnymontana** [join-monster/join-monster#177]
Is it possible to use Join Monster with multiple databases? One of the benefits of GraphQL is the ability to fetch data from multiple data sources. Let's says I have a Postgres DB and a MongoDB instance. The `Person` GraphQL type is resolved from Postgres and the `Blog` type is resolved from Mongo.

With the standard GraphQL approach I would have code to query Mongo in my `Blog` resolver functions and code to query Postgres in my `Person` resolver. Is there a way to use Join Monster to define the resolvers for `Person`, but write my own resolvers for `Blog` type?

**Comment by acarl005** [comment]
Yes. See [this page in the docs](http://join-monster.readthedocs.io/en/latest/how-it-works/)

> "You can write custom resolvers like you normally would that gets data from anywhere else. Join Monster is just a way of fetching data, it will not hinder your ability to write your other resolvers. You can also have your fields get data from a column and apply a resolver to modify, format, or extend the data."

Join Monster will not attempt to handle object types that lack a `sqlTable` property. [This option](http://join-monster.readthedocs.io/en/latest/misc/) was added in case an object type should *sometimes* be handled by join monster and *sometimes not*.
