### ISSUE TITLE
Compatibility issues with Proxy

### ISSUE THREAD

**Issue by tslater** [join-monster/join-monster#187]
I've nearly completed my quest of getting join-monster to run in an embedded, React Native environment. On newer versions of iOS, things are working great. Android (and older iOS versions), however, lack support for `Proxy`. It tried https://github.com/GoogleChrome/proxy-polyfill, but no luck. I called `import Proxy from "proxy-polyfill/proxy";` which remove the error for Proxy not being defined, but doesn't make it work.

Here is the code using Proxy, just one call:

https://github.com/stems/join-monster/blob/bc9b200ec2e9645b7bd2c45a7135fd2a798d9e40/src/query-ast-to-sql-ast/index.js#L534

I don't understand this part of the codebase very well. Any advice on how to better polyfill or alternatives to using Proxy, would be awesome!

**Comment by acarl005** [comment]
That part would by easily replaced. It's basically just there to mimic something like a defaultdict in Python. Why isn't it working? Is there an error message?

**Comment by tslater** [comment]
I just got my answer: The polyfill needs to know the keys/properties at runtime:
https://github.com/GoogleChrome/proxy-polyfill/issues/31.

It's a shame! Polyfill is a really clean way of doing this. Could we replace it with something like:

```
    const depsByTable = new Proxy({}, { get: (target, name) => name in target ? target[name] : new Set() })

    // loop thru each child which has "columnDeps", remove it from the tree, and add it to the set
    for (let i = children.length - 1; i >= 0; i--) {
      const child = children[i]
      if (child.type === 'columnDeps') {
        const keyName = child.fromOtherTable || ''
        child.names.forEach(name => {
          depsByTable[keyName] = depsByTable[keyName].add(name)
        })
        children.splice(i, 1)
      // or if its another table, recurse on it
      } else if (child.type === 'table' || child.type === 'union') {
        pruneDuplicateSqlDeps(child, namespace)
      }
    }
```

**Comment by tslater** [comment]
I just got my answer: The polyfill needs to know the keys/properties at runtime:
GoogleChrome/proxy-polyfill#31.

It's a shame! Polyfill is a really clean way of doing this. Could we replace it with something like:
```
    const depsByTable = {}

    // loop thru each child which has "columnDeps", remove it from the tree, and add it to the set
    for (let i = children.length - 1; i >= 0; i--) {
      const child = children[i]
      if (child.type === 'columnDeps') {
        const keyName = child.fromOtherTable || ''
        child.names.forEach(name => {
        if(!depsByTable[keyName])
            depsByTable[keyName] = new Set()
          depsByTable[keyName] = depsByTable[keyName].add(name)
        })
        children.splice(i, 1)
      // or if its another table, recurse on it
      } else if (child.type === 'table' || child.type === 'union') {
        pruneDuplicateSqlDeps(child, namespace)
      }
    }
```
I haven't run the tests yet, but it ran fine in my example.

**Comment by acarl005** [comment]
Version **2.0.5** is published. Should fix this ✔️
