### ISSUE TITLE
Latest release (2.0.5) missing files

### ISSUE THREAD

**Issue by tslater** [join-monster/join-monster#190]
First off, thanks so much for your responsiveness! This has been a really great experience. 

I noticed your npm release and immediately went to try it, unfortunately, the package seems void of all dist files. After starting a new project and installing (with Yarn or npm), I get this:
```
bunker:empty admin$ ll node_modules/join-monster/
total 80
drwxr-xr-x   5 admin  staff   170B Aug 11 11:54 .
drwxr-xr-x  10 admin  staff   340B Aug 11 11:54 ..
-rw-r--r--   1 admin  staff   1.1K Aug 11 11:14 LICENSE
-rw-r--r--   1 admin  staff    14K Aug 11 11:14 README.md
-rw-r--r--   1 admin  staff    20K Aug 11 11:54 package.json
bunker:empty admin$ 
```

**Comment by acarl005** [comment]
Thats weird... I'll check it out.

**Comment by acarl005** [comment]
Can you try with 2.0.5-1?

**Comment by tslater** [comment]
That loads the files

**Comment by tslater** [comment]
It works great too! On iOS and Android, React Native!

**Comment by acarl005** [comment]
Well that's a first. That's great to hear!
