### ISSUE TITLE
join condition column name not quoted

### ISSUE THREAD

**Issue by Chun-Yang** [join-monster/join-monster#192]
I am using pg. Pg will convert column names to lowercase if its not quoted.

This is the sql I get:
```
SELECT
  "users"."id" AS "id",
  "users"."age" AS "age",
  "profile"."id" AS "profile__id"
FROM "User-150a5920-7ef0-11e7-a192-ebd0428dcb38" "users"
LEFT JOIN "Profile-150a5920-7ef0-11e7-a192-ebd0428dcb38" "profile" ON "users".id = "profile".userId
error: column profile.userid does not exist
```

This is the error I get
```
error: column profile.userid does not exist
```

I think we need to quote the column name.

**Comment by acarl005** [comment]
That looks like `profile.userid` came from the user-defined `sqlJoin` function. Since this is provided by the user, it cannot be automatically quoted. You must quote it yourself.

**Comment by Chun-Yang** [comment]
I see. Thank you!
