### ISSUE TITLE
A way to perform raw select

### ISSUE THREAD

**Issue by idangozlan** [join-monster/join-monster#195]
I wonder if there's a way to perform raw select, for example if I need to select UNIX_TIMESTAMP(column) on db (I know that I can do it on the graphql but prefer the DB to handle some conventions).

Thanks!

**Comment by acarl005** [comment]
There is. You can use `sqlExpr` ([Docs](http://join-monster.readthedocs.io/en/latest/field-metadata/#computed-columns)). It will interpolate raw *SQL expressions* into the `SELECT` clause.

```js
{
  sqlExpr: table => `UNIX_TIMESTAMP(${table}.column)`
}
```
