### ISSUE TITLE
How to handle many to one with no unique key but unique fields combination

### ISSUE THREAD

**Issue by idangozlan** [join-monster/join-monster#196]
Hi,

I have table with the following columns: userID, key, value.

I wish to join all the records that belong to specific userID as a column on User query, is that possible? how should I handle the uniqueKey which is combination of userID+key?

Thanks

**Comment by acarl005** [comment]
You can choose "composite keys", or combinations of columns to form unique values by passing an array for `uniqueKey` ([docs](http://join-monster.readthedocs.io/en/latest/map-to-table/#composite-keys)).

If you want to expose combinations of columns in your API as fields, you can use `sqlExpr` to concatenate them in a raw SQL expression or do it in JavaScript in the resolver using `sqlDeps`.
