### ISSUE TITLE
Question - Aggregation Tricks - JSON_VALUE (mariadb) = json_agg???

### ISSUE THREAD

**Issue by MichelDiz** [join-monster/join-monster#199]
Hi,

The mariadb's "JSON functions and dynamic columns" are similar to PostgreSQL json_agg?
And would work on Join Monster?

ref: https://mariadb.com/database/topics/json

Best Regards

**Comment by acarl005** [comment]
`sqlExpr` allows you to enter any raw expression in SQL, including function calls. This *should* include the JSON functions. Keep in mind that you may or may not need to JSON results depending on your database driver.
