### ISSUE TITLE
When using junction, orderBy function is not triggered

### ISSUE THREAD

**Issue by idangozlan** [join-monster/join-monster#200]
When I'm using junction, orderBy function (which triggering without the junction) is not triggering, is that intend behavior or a bug?

**Comment by acarl005** [comment]
Sounds like it may be a bug! Can you post your source code? Also, can you run your app with the following environment variable `DEBUG=join-monster`, trigger the bug again, and post the additional output?

**Comment by idangozlan** [comment]
I'm working on pretty sensitive information, do we have a test env like runkit or something with boilerplate of join monster?

**Comment by acarl005** [comment]
Unfortunately not. Any chance you could obfuscate the sensitive parts? Or maybe recreate the bug on a toy example?

**Comment by idangozlan** [comment]
will try to do it asap. will keep post.

**Comment by idangozlan** [comment]
My bad, had to create common method of orderby and share it between the schema/query.
