### ISSUE TITLE
Multiple edges between the same two nodes are not resolved

### ISSUE THREAD

**Issue by bw** [join-monster/join-monster#201]
If two nodes have more than one edge in between, and we are using join-monster's junction join/batch with edge fields, then the additional edges will be swallowed.

### Example

For example, let's say that we have two Users (table `users`) and we define relationships between them (table `user_relationships`) with a "relationship" type. This is a contrived example, but let's say these two users have two relationships-- one is "coworker" and one is "friend".

To fetch these from the database, we put these fields on the edge table `user_relationships` and then resolve them onto the GraphQL connection edge:

**Edge fields on the connection:**

```graphql
{
  user {
    id
    name
    usersConnection {
      edges {
        relationshipType  # Can be `coworker` or `friend`
        node {
          id
          name
        }
      }
    }
  }
}
```

Actually, for the purpose of this example, since the edge fields are [rendered onto the destination node](https://github.com/stems/join-monster/issues/155) for now, a working example would look as so:

**Workaround GraphQL query, with edge fields on node:**

```graphql
{
  user {
    id
    name
    usersConnection {
      edges {
        node {
          id
          name
          relationshipType  # From the edge; can be `coworker` or `friend`
        }
      }
    }
  }
}
```

Since there are two relationships, in this use case we'd need for both of those relationships to come back:

**Expected behavior:**

```json
{
   "user": {
      "id": 1,
      "name": "Adam",
      "usersConnection": {
         "edges": [
            {
               "node": {
                  "id": 2,
                  "name": "Bobby",
                  "relationshipType": "coworker"
               }
            },
            {
               "node": {
                  "id": 2,
                  "name": "Bobby",
                  "relationshipType": "friend"
               }
            }
         ]
      }
   }
}
```

But join-monster swallows the second relationship and only gives us back the first one that it finds in the database:

**Actual (incorrect) behavior:**

```json
{
   "user": {
      "id": 1,
      "name": "Adam",
      "usersConnection": {
         "edges": [
            {
               "node": {
                  "id": 2,
                  "name": "Bobby",
                  "relationshipType": "coworker"
               }
            }
         ]
      }
   }
}
```

----

The current workaround is to define the edge itself as a node. So we have User object types, linked with the `users` table, and UserUserEdge object types, linked with the `user_relationships` table. This works for simple cases but (a) breaks pagination; (b) breaks filtering, however it is implemented; and (c) breaks sorting.

Therefore some sort of native join-monster support for use cases like this would be very nice. Looking at the source, I believe this is something related to the way that the SQL response is being converted back to the GraphQL AST.

Happy to provide more information if it is helpful. Thanks!

**Comment by acarl005** [comment]
What have you indicated as your `uniqueKey` for each type?

**Comment by bw** [comment]
For users, `id`. For the table of edges, `id` as well. They are all unique.

**Comment by acarl005** [comment]
Ah yes. When using a `junction`, the nodes on the other side of the edge will be made unique, as no meaningful information is assumed to be inside the junction table other than a link between the nodes. Currently, if there is meaningful information in that junction, the junction table itself must be made into a `GraphQLObjectType`.

Alternatively, if there was a way to specify unique keys that combine columns from the node *and* the junction, that would allow you to keep the interface as is. That's a potential new feature.

**Comment by bw** [comment]
Gotcha. Defining the junction table as an GraphQLObjectType is what we're doing right now; obviously that's not perfect because we lose some of the pagination and filtering benefits.

Keep us updated on the progress for the new feature!

Thanks.
