### ISSUE TITLE
Namespace include fields on a junction

### ISSUE THREAD

**Issue by switz** [join-monster/join-monster#202]
Here's something I'm trying to figure out: let's say I have a SQL table to mimic a basketball game.

tables:
```
player (id)
match (id)
player_match (player_id, match_id, points, assists, blocks, steals)
```

Players can have many matches and each match can have many players.

So I set up my graphql/join-monster and add a field to player called `matches` (junction) and a field to match called `players` (junction).

Inside a player's matches, I can include fields `points, assists, blocks, and steals` which refer to that players stats for each match.

Inside a match's players, I can also include fields `points, assists, blocks, and steals` which refers to each players stats for that match.

It would be nice if I could namespace those includes under a graphql schema called `Stats`, that way, if I want the player's stats (or the players in a match's stats), I don't have to hamfist the `points, assists, blocks, and steals` fields into both the `Player` schema and the `Match` schema (which are not necessarily relevant to those entities unless in the junction context above). I would then be able to create a `Stats` schema and request it if needed. Granted, this still leaves me with a latent `stats` field that may not be relevant outside of the junction context, but at least its not the 40+ fields I would need in a real-world context.

Does this make sense or am I missing something obvious that I should be doing differently? I'm new to graphql and subsequently join-monster, so feel free to point me in the right direction. Cheers.

**Comment by switz** [comment]
@acarl005 do you have any insight you can share here -- am I thinking about this correctly or should I perhaps be moving my junction fields into a separate table?

**Comment by acarl005** [comment]
@switz Can you try it with the option `minify: true`? That should generate aliases that are much less likely to clash with your table names. [docs](http://join-monster.readthedocs.io/en/latest/API/#joinMonster)
