### ISSUE TITLE
Provide JSON Query Support

### ISSUE THREAD

**Issue by jovincroninwilesmith** [join-monster/join-monster#21]
It would be great if I could easily return nested values inside of a JSON column.

**Comment by dreamcodez** [comment]
This should most likely be the job of the database adapter -- not sure..

**Comment by acarl005** [comment]
If your field depends on only a single property within a Postgres JSONB column, it may be a slight over-fetch to get the whole column instead of just that one property.

For now you can just make the column a dependency, and use the resolver to parse the JSON and get that property.

**Comment by naturalethic** [comment]
My mysql adapter spits me a javascript object for my json fields, and I provide a type that simply passes the value through, like so:

```
const GraphQLJson = new GraphQLScalarType({
  name: 'Json',
  serialize(value) {
    return value
  },
  parseValue(value) {
    return value
  },
  parseLiteral(ast) {
    return ast.value
  },
})
```

You could have this parse/stringify if you adapter doesn't do that for you.

**Comment by acarl005** [comment]
The new `sqlExpr` property in **v0.7.0** allows the interpolation of computed columns via raw SQL expressions. see this page in the [docs](http://join-monster.readthedocs.io/en/latest/field-metadata/#computed-columns).

Now something like this is possible:

```js
fields: () => ({
  someJSONprop: {
    type: GraphQLString,
    sqlExpr: table => `${table}.json_column_name ->> 'propName'`
  }
})
```
