### ISSUE TITLE
Missing Lodash library, crash resolve union

### ISSUE THREAD

**Issue by arialpew** [join-monster/join-monster#212]
There is no mention of Lodash in package.json

You can add "lodash-function-name" for smaller bundle size -> "chain", "filter", "flatMap".

"peerDependencies" in package.json can probably work but i don't know it.

Without Lodash, resolver union don't work (try it with a small one-to-many User/Client on latest release).

```(0 , _lodash.chain)(...).filter(...).flatMap is not a function (resolver-union.js - 58).```

Adding Lodash with "npm i lodash --save" solve this.

Nice project, love the concept 👍

**Comment by acarl005** [comment]
Should be fixed in latest version **v2.0.10**.
