### ISSUE TITLE
how to use group by in join-monster?

### ISSUE THREAD

**Issue by fangjj** [join-monster/join-monster#222]
I want to use group by in join-monster, but I can't find anything instruction about it in the docs.
```javascript
new GraphQLObjectType({
  description: 'global query object',
  name: 'Query',
  fields: () => ({
    //...
    groupNum: {
      type: new GraphQLList(new GraphQLObjectType({
        name: "groupNum",
        fields: {
            account_id: {
              type: GraphQLInt
            },
            numComment: {
              type: GraphQLInt
            },
            /*
            user: {
              type: User
            }
            */
        },
      })),
      resolve: () => knex.raw(`select account_id, count(comment_id) as numComment from likes where comment_id > 5 group by account_id having count(comment_id) > 10

`).then(num => num)
    }
  })
})
```
I execute sql by knex in resolve, but i want this query, but have no idea get  graphqlobject ‘user’ ?
```javascript
query{
groupNum {
    account_id
    user{
        fullName,
        //...
    }
    numComment
  }
}
```
so, can you help me out ? thank you!

**Comment by acarl005** [comment]
The support for `GROUP BY` isn't fully there yet. Currently you can do *some* types of aggregation by putting it in a subquery, [like so](http://join-monster.readthedocs.io/en/latest/aggregation/#correlated-subqueries). But a more general method has not been conceived.

**Comment by fangjj** [comment]
ok, I create new graphqlobject and run group by in sqlTable, then sqlJoin the User, it work.
