### ISSUE TITLE
Sql Batch based on non unique key compares (but with other conditions)

### ISSUE THREAD

**Issue by idangozlan** [join-monster/join-monster#223]
Hi,

I wonder if there's a way to get batch with other conditions then unique keys, my case is:
I'm fetching object based on unique ID that has date field, and I want to fetch all other objects that they're date is lower then this object.

Im using MariaDB, when using just sqlJoin it's working perfect but without limit option. 
Limit is not available (even though it's possible to perform this query with MariaDB).

Thanks.

**Comment by nicoabie** [comment]
I'm not sure I understand this, can you provide an example using https://github.com/join-monster/join-monster-sscce?
