### ISSUE TITLE
add global config for joinMonster

### ISSUE THREAD

**Issue by fangjj** [join-monster/join-monster#224]
I want to global config the joinMonster options for dialect or minify,  then in resolve i can omit the options. of course, you can config  joinMonster options alone, the options cover the global config only work in this one resolve.

**Comment by acarl005** [comment]
Agreed that this would be a nice enhancement.

**Comment by GlennMatthys** [comment]
You can just wrap your join monster call like this:

```
const joinMonster = require('join-monster').default;

const myJoinMonster = (obj, args, ctx, info) => joinMonster(info, ctx, sql => ctx.db.raw(sql).then(dbResult =>dbResult), { dialect: 'pg' });
```

And then in your resolvers:

```
const resolvers =
{
    Query:
    {
        posts: myJoinMonster,
        users: myJoinMonster
    },
    ...
}
```
Note: I quickly wrote this without IDE and testing so it might not work copy/pasting, but I'm trying to illustrate the method of how to get this done.

So with this approach I see no need for listening for some kind of global configuration, what do you think @acarl005?

**Comment by nicoabie** [comment]
Closing as @GlennMatthys provided a solution.
