### ISSUE TITLE
Does this work with Oracle 11g or 12c +?

### ISSUE THREAD

**Issue by jeveloper** [join-monster/join-monster#225]
Has anyone tried this with oracle ?

I saw that it is supported and i have 12.2C , unfortunately stuck with oracle, running on AWS RDS.
Just wanted to get an idea if there are any known limitations or issues with Oracle. I think this is the only graphql project that has oracle support.

Would be great to get feedback before i spend a lot of time trying.

Thank you very much for this amazing project !

**Comment by acarl005** [comment]
Oracle >= 12 is supported. 11g is not because `CROSS APPLY` had not been implemented yet. You can find version caveats in [the docs](http://join-monster.readthedocs.io/en/latest/dialects/). If you use 12.1, you might run into [this Oracle bug](https://community.oracle.com/thread/3998288).
