### ISSUE TITLE
Join field (instead of object) to schema

### ISSUE THREAD

**Issue by idangozlan** [join-monster/join-monster#227]
Is there any way to join non object (string) to schema?

All I can see on the docs is about [Joining objects](https://join-monster.readthedocs.io/en/latest/start-joins/) but I need to join single field (string) from another table.

Thanks

**Comment by acarl005** [comment]
Ah yes, this is a similar issue to #57. Although in that case a workaround was found, I think this functionality may need to be a first-class citizen. This feature needs to be reconsidered.

**Comment by idangozlan** [comment]
Thanks, I can try help implement it.

**Comment by horakmx** [comment]
Same problem is discussed here: #311, #198

**Comment by nicoabie** [comment]
Closing as duplicate of #198
