### ISSUE TITLE
conditional SqlBatch

### ISSUE THREAD

**Issue by idangozlan** [join-monster/join-monster#228]
Hi,

I wonder if there's any feature of performing the sqlBatch conditionally?
Say we perform the first query, and certain batch (of many) which comes after it, should happens only if field `type` (which is part of the response) equals something.

Thanks

**Comment by nicoabie** [comment]
Hi! I don't understand this. I'm closing for now but feel free to reopen with a detailed example using https://github.com/join-monster/join-monster-sscce
