### ISSUE TITLE
Querying an interface

### ISSUE THREAD

**Issue by khell** [join-monster/join-monster#229]
Does `join-monster` support querying an interface at the root? It seems interfaces work as fields for other types, but if I try to root query an interface I get this error:
```
"message": "Must call joinMonster in a resolver on a field where the type is decorated with \"sqlTable\".",
```

**Comment by ctoledoperez** [comment]
Any update on this? Jumped on same problem. Tried with unions too and same problem.

**Comment by nicoabie** [comment]
This should be fixed now, if not feel free to provide a https://github.com/join-monster/join-monster-sscce
