### ISSUE TITLE
best way to join from a custom resolver to a JM resolver (and vice versa)

### ISSUE THREAD

**Issue by bradzacher** [join-monster/join-monster#235]
Say we have 3 types - A, B and C.
A has a custom resolve function as it's got some weird SQL requirements.
B is a type backed fully by JM config + resolver.
C again has a custom resolve fn.

A is related to B, B is related to C.

B to C seems simple enough (B's result is passed to C's resolve function from which it can be handled).
But what's the best way to make a join from A to B?

You can't pass the `source` into the JM function.
`jmIgnoreTable` is used to ignore a table joining from (i.e. could be used for the B to C join).

**Comment by maksis** [comment]
@bradzacher did you find any solution for this?

**Comment by bradzacher** [comment]
it is currently not possible using join-monster.

**Comment by nicoabie** [comment]
I'm closing this one because I believe it is the same described here https://github.com/join-monster/join-monster/issues/493
