### ISSUE TITLE
Pagination question

### ISSUE THREAD

**Issue by yury** [join-monster/join-monster#238]
Turns out that traditional paging sometimes is better (if you want to show all pages).

I tried to to implemented with join-monster and stuck.

1. I tried to append LIMIT and OFFSET to generated SQL and it worked. But I can't find a place where I can inject `count(*) OVER() AS total`.
2. I tried to query with `knex` in resolver, but can't find a good way to map queryAST to select sql fields.

Any help would be great.

**Comment by amosyuen** [comment]
@yury did you ever figure this out?

**Comment by acarl005** [comment]
Can you clarify what you mean by "traditional paging"? Using `LIMIT` and `OFFSET` is an option provided by JM [(docs)](http://join-monster.readthedocs.io/en/latest/pagination/#2-integer-offset-paging)

**Comment by nicoabie** [comment]
Closing as there was no answer in 6 years
