### ISSUE TITLE
Got error with mysql and mariadb

### ISSUE THREAD

**Issue by halallahh** [join-monster/join-monster#24]
I tried with **sqlite** and it work fine but with **mysql/mariadb** I got these error.

#### Error:
`ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near`

#### Full error:
```
"errors": [
    {
      "message": "SELECT\n  \"todos\".\"id\" AS \"id\",\n  \"todos\".\"task\" AS \"task\",\n  \"comments\".\"id\" AS \"comments__id\",\n  \"comments\".\"title\" AS \"comments__title\"\nFROM todos AS \"todos\"\nLEFT JOIN comments AS \"comments\" ON \"todos\".id = \"comments\".todoId - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.\"id\" AS \"id\",\n  \"todos\".\"task\" AS \"task\",\n  \"comments\".\"id\" AS \"comments__id\",\n' at line 1",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
```

#### version:
join-monster ^0.4.2
MySQL 5.7.16
MariaDB 10

**Comment by acarl005** [comment]
I see. The problem is the different meaning of double quotes in MySQL/MariaDB.

In SQLite3 and Postgres, which is what Join Monster is tested on, double quotes are used around an identifier to escape certain characters, like whitespace and capital letters. However, MySQL uses double quotes for a string literal. For MySQL, backticks should be used instead.

This means a new dialect will need to be introduced for MySQL/MariaDB. It's a simple fix and I can get around to it in a few days.

**Comment by acarl005** [comment]
I added a MySQL/MariaDB dialect.

To use it you must pass `joinMonster` an **options Object** with a `'dialect'` property set to `'mysql'`. See [the API docs](http://join-monster.readthedocs.io/en/latest/API/#joinMonster) for details.

I don't know which library you are using to connect to your database. If you are using `knex`, there is one thing you should watch out for. `knex.raw` returns different objects based on the knex dialect being used. It may not work with the exact code from the docs. Just double check the shape of that object before returning it from the callback. You may have to change this...

``` js
return joinMonster(resolveInfo, {}, sql => {
    return knex.raw(sql)
})
```

... to something like this...

``` js
return joinMonster(resolveInfo, {}, sql => {
    return knex.raw(sql).then(result => result[0])
}, { dialect: 'mysql' })
```

Please let me know if this works. If so, the issue can be closed.

**Comment by halallahh** [comment]
Works perfectly!
