### ISSUE TITLE
Computing value based on current object and joined table

### ISSUE THREAD

**Issue by nakedible-p** [join-monster/join-monster#242]
I'd like to create a GraphQL field where the value depends on another field resolved from SQL, and actually resolved from a JOIN.

In simple terms, I have table `thingy` with columns `id`, `type`, `foo`, and table `thingyType` with columns `id`, `defaultFoo`. Since I have the join specified on type, I can do graphql `{ id, foo, type { defaultFoo } }` and then do `data.foo || data.type.defaultFoo` on the client side logic. But instead I'd like to add a field `calculatedFoo`, which would resolve to the same thing on the server side.

What is the best way to do this?

**Comment by theobat** [comment]
I think you should either rely on a custom query or on a view. The unclear thing is whether you want the join to happen for every row or just on those where a default value is required. I could see something like:

```
{
sqlTable: SELECT id, type, COALESCE(foo, defaultFoo) as realfoo FROM thingy LEFT JOIN thingyType ON thingy.type IS NULL
}
```

of course you lose one of the benefits of join monster here that is joining only when you request the data, but perhaps thingy and thingyType should be coupled together in your data model
