### ISSUE TITLE
Allow limit without pagination on `sqlite3` or `mysql`

### ISSUE THREAD

**Issue by mitjade** [join-monster/join-monster#243]
I would like to use `join-monster` with `sqlite3` or `mysql` database, but it prevents me setting the `limit`.

You state in the docs, that limit can only be used if pagination is supported for your SQL dialect. But I do not see why not allowing the use of limit with `sqlite3` or `mysql` if you want to use it without pagination?

**Comment by mitjade** [comment]
Created a  PR #264, that would allow this.

Please comment if this would be acceptable, or some other changes are needed.

**Comment by iAlirezaKML** [comment]
I think changing `await` to `yield` solves the `Test failed` problem.

**Comment by mposborne** [comment]
Rather than modify code functions i've been able to setup a new MySQL dialect to do just this. I'm sure sqlite3 will be similar.

This is setup for full pagination so you can provide an offset if you want, but it is optional.

https://github.com/RollHQ/join-monster-mysql
