### ISSUE TITLE
Optional double quotes for case insensitive columns?

### ISSUE THREAD

**Issue by renato** [join-monster/join-monster#248]
I have a GraphQL object Activity with a field named "plannedDate", but I personally prefer my database to be case insensitive, so my PostgreSQL field is planneddate, without double quotes.

The problem is, if I use Join Monster with the "plannedDate" GraphQL field, it assumes it's the same case-sensitive name in the database, which it isn't in my case.

I'm currently stripping double quotes but only for these fields (the "'s from the aliases must be kept), but is it possible to achieve the same thing without removing the quotes?

Thanks.

**Comment by leonardfactory** [comment]
Have you tried with `sqlColumn` metadata?  (`sqlColumn: "planneddate"`)

From the docs:

```js
  email: {
      type: GraphQLString,
      // if the column name is different, it must be specified specified
      sqlColumn: 'email_address'
    },
```

**Comment by renato** [comment]
Yes, this would be a solution, but it would be easier to just ignore the double quotes for the identifiers instead of setting sqlColumn for every camelCase field.

Knex supports a "wrapIdentifier", which can be used to do it or convert camelCase to snake_case, for example. https://github.com/tgriesser/knex/issues/2084

Anyway, I'm using the camelCase convention in the database too for now.

**Comment by renato** [comment]
I'm currently auto-generating the join-monster `sqlColumn` information for all the fields using the keys in `schema._typeMap.TypeName._fields`, converting to whatever I need.

This approach in addition to using `wrapIdentifier` allows me to use a camelCase -> snake_case or camelCase -> lowercase correctly.

It would be great to drop this custom code and use something standard from join-monster.

**Comment by nicoabie** [comment]
JM supports a way of overriding the column name. I think adding more on JM's part is making the API unnecessarily complex
