### ISSUE TITLE
"Must call joinMonster in a resolver on a field..." error appears when code is bundled/minified

### ISSUE THREAD

**Issue by smoll** [join-monster/join-monster#250]
Not sure how much of this detail is relevant, so I'm erring on the side of more in case something makes a lightbulb go off in someone's head...

Anyway, I'm using join-monster with React Native, with the sqlite dialect and a library that exposes a [sqlite javascript interface](https://github.com/andpor/react-native-sqlite-storage). My code works perfectly fine in development mode, however, when I packaged a binary and released it via TestFlight, all queries fail with the following error:

```
{"location":{},"loading":false,"error":
{"line":413,"column":1166,"sourceURL":"/Users/s/Library/Developer/CoreSimulator/Devices/B9F2AB
25-0471-4287-9DEA-2AEF3FBA263C/data/Containers/Bundle/Application/632B07CA-C0FE-4885-8052-15C9CA462308/test.app/main.jsbundle",
"graphQLErrors":[{"message":"Must call joinMonster in a resolver on a field where the type is decorated with \"sqlTable\".",
"locations":[{"line":2,"column":3}],"path":["categories"]}],"networkError":null,
"message":"GraphQL error: Must call joinMonster in a resolver on a field where the type is decorated with \"sqlTable\"."}}
```

My QueryRoot.js file looks like:

```
import {
  GraphQLObjectType,
  GraphQLString,
  GraphQLInt,
  GraphQLFloat,
  GraphQLID,
  GraphQLList,
  GraphQLNonNull
} from 'graphql'
import {
  fromGlobalId,
  globalIdField,
  connectionArgs,
  forwardConnectionArgs,
  connectionDefinitions,
  connectionFromArray
} from 'graphql-relay'

import joinMonster from 'join-monster'
import sqlite3Module from 'join-monster/dist/stringifiers/dialects/sqlite3'

import Category, {CategoryConnection} from './Category'
import OfflineDatabase from './OfflineDatabase'
import { nodeField } from './Node'

const db = new OfflineDatabase()
const options = { dialectModule: sqlite3Module }

export default new GraphQLObjectType({
  description: 'global query object',
  name: 'Query',
  fields: () => ({
    version: {
      type: GraphQLString,
      resolve: () => joinMonster.version
    },
    // implement the Node type from Relay spec
    node: nodeField,
    categories: {
      // Top-level connection is possible, cf. https://github.com/stems/join-monster/issues/102#issuecomment-289141770
      type: CategoryConnection,
      args: {
        ...connectionArgs,
        term: {
          description: "A search term to filter results by",
          type: new GraphQLNonNull(GraphQLString)
        }
      },
      sortKey: {
        order: 'desc',
        key: 'id'
      },
      sqlPaginate: false,
      where: (categoryTable, args, context) => {
        if (args.term) return `UPPER(${categoryTable}.name) LIKE "%${args.term.toUpperCase()}%"`
      },
      resolve: (parent, args, context, resolveInfo) => {
        return joinMonster(resolveInfo, context, sql => db.run(sql), options).then(data => connectionFromArray(data, args))
      }
    },
    category: {
      type: Category,
      args: {
        id: {
          description: "The category's ID",
          type: GraphQLID
        }
      },
      // this function generates the WHERE condition
      where: (categoryTable, args, context) => { // eslint-disable-line no-unused-vars
        if (args.id) {
          const { type, id } = fromGlobalId(args.id)
          return `${categoryTable}.id = ${id}`
        }
      },
      resolve: (parent, args, context, resolveInfo) => {
        return joinMonster(resolveInfo, context, sql => db.run(sql), options)
      }
    },
  })
})
```

At first I thought my error was related to https://github.com/stems/join-monster/issues/102 but it looks like the same error happens regardless of whether I am querying a connection field (querying either `category` or `categories` displays the same error), plus my code pretty much matches the one proffered by @acarl005

I am able to reproduce this issue locally only if I do a ["release build" in Xcode ](https://stackoverflow.com/a/40037463/3456726), the difference being, according to https://stackoverflow.com/a/14473372/3456726, that there are some Obj-C compiler optimizations happening. My instinct is that the real, substantive difference is that either:

a) there is an error in my code, that is simply getting swallowed up in dev, or
b) when a production build is performed, some assertions (or some other kind of checks) turn into runtime errors

Any insight that you guys can provide, or ideas on how I can debug this further, would be greatly appreciated. Been racking my brain on this bizarre bug for a few days with hardly any progress to show for it... I can create a minimal React Native repro if you think that would be helpful at all (but can't use https://snack.expo.io/ because there are some nodejs globals that join-monster depends on that I can't shim unless I control the RN build)

**Comment by smoll** [comment]
Here's a minimal repro if anyone wanted to look at the complete code: https://github.com/smoll/monster

It works fine locally (`yarn && yarn ios`) but if you load up https://expo.io/@smoll/monster

it shows the same error:

```
{"count":0,"loading":false,"error":{"line":665,"column":1166,"sourceURL":"https://d1wp6m56sqw74a.cloudfront.net:443/%40smoll%2Fmonster%2F0.1.0%2F3d5d8823e76b2361072b07e8087ef8d3-21.0.0-ios.js",
"graphQLErrors":[{"message":"Must call joinMonster in a resolver on a field where the type is decorated with \"sqlTable\".",
"locations":[{"line":2,"column":3}],"path":["contents"]}],"networkError":null,
"message":"GraphQL error: Must call joinMonster in a resolver on a field where the type is decorated with \"sqlTable\"."}}
```

**Comment by smoll** [comment]
So, another data point to add here, after I asked Expo for [help](https://forums.expo.io/t/how-to-debug-differences-between-dev-app-published-app/4010/7): apparently, when I minify in dev, I can reproduce this issue locally (!)

Is there something in my code or this package that would cause this error to manifest when minified? Anyway, I'll keep digging on my end.

**Comment by leonardfactory** [comment]
After checking source code, I've seen that joinMonster is relying on GraphQL classes `constructor.name` in order to distinguish between tables and simple fields aka columns, expressions, etc. You can see this behaviour in the following method: 

```js
  // is this a table in SQL?
  if (
    !field.jmIgnoreTable &&
    TABLE_TYPES.includes(gqlType.constructor.name)
    && config.sqlTable
  ) {
```
Source: https://github.com/stems/join-monster/blob/cfa3537fd3e2f10f57bab2e75a85322acae5590c/src/query-ast-to-sql-ast/index.js#L152 

After minification however, it's possible that the constructor names are mangled away, so check is going to fail and joinMonster cannot recognize object as table. 

Actually used `TABLE_TYPES` (so constructor names) are: 
https://github.com/stems/join-monster/blob/cfa3537fd3e2f10f57bab2e75a85322acae5590c/src/query-ast-to-sql-ast/index.js#L23

You can try disable `mangle` for these GraphQL required classes, passing the `mangle.except` option to `UglifyJS`: https://github.com/mishoo/UglifyJS2/issues/671#issuecomment-90727732

I'm not sure about this, but it's worth a try. Let me know if it worked!

*PS: This sounds like a situation that doesn't happen frequently since it's not common to minify code on server-side. However RN seems like a plausible use case so we should find another solution instead of relying on `constructor.name`(if this is the problem) to detect tables.*

**Comment by smoll** [comment]
Sorry, just saw this @leonardfactory -- good catch noticing https://github.com/stems/join-monster/blob/cfa3537fd3e2f10f57bab2e75a85322acae5590c/src/query-ast-to-sql-ast/index.js#L152 -- I'll give it a shot when I get back to my desk!

**Comment by smoll** [comment]
Sorry for the late reply but @leonardfactory you hit the nail on the head. Once I figured out how to change the mangle config to ignore those classes, the error went away. Thanks a ton!

**Comment by Traviskn** [comment]
@smoll I've run into this issue as well, how did you go about changing the mangle config to ignore those classes?

**Comment by smoll** [comment]
Hey @Traviskn - the mangle config you want is:

```
mangle: { reserved: ['GraphQLObjectType', 'GraphQLUnionType', 'GraphQLInterfaceType'] }
```

because this was for a React Native app and they don't let you touch the mangle config directly, I wrote a small script to hack the `metro-bundler` minifier script: https://gist.github.com/smoll/94365ce78873969e734adaef8dfc0325

**Comment by Traviskn** [comment]
@smoll thanks for sharing, this is awesome!

**Comment by enaeher** [comment]
For the benefit of others running into this issue, we had to exclude not only `GraphQLObjectType`, `GraphQLUnionType`, and `GraphQLInterfaceType` (mentioned above) from the minification, but also `GraphQLSchema`, `GraphQLString`,`GraphQLBoolean`, and `GraphQLList`.
