### ISSUE TITLE
Sequelize integration

### ISSUE THREAD

**Issue by alexisgahon** [join-monster/join-monster#256]
Hi,
We want to use join-monster in our project. But we are deeply dependent on Sequelize.

Do you have any plan of a deep integration of Sequelize, like model introspection ?
Or maybe you have another way use join-monster and Sequelize together ?

**Comment by mposborne** [comment]
I see this question is quite old now but i've managed to figure this out as we are also using Sequelize. Hopefully you figured this out anyway as well but here's an answer for others who come across this issue:

```
resolve: (table, args, context, resolveInfo) => {
  const sequelize = require('../../../config/database');
  return joinMonster(resolveInfo, {}, sql => {
    return sequelize.query(sql).then(function(result) {
      return result[0];
    });
  }, {dialect: 'mysql'});
},
```

Basically, send the SQL through to Sequelize as a raw query and then grab the first item in the returned array. Set the dialect appropriately of course.

**Comment by acarl005** [comment]
This is out of scope for this project. One of the goals of JM is to sort of make GraphQL itself your ORM. Your GraphQL types already map your tables to objects, and JM's job is to write the queries to bring those together.
