### ISSUE TITLE
Would it be possible for Join-Monster to support Cypher?

### ISSUE THREAD

**Issue by MichelDiz** [join-monster/join-monster#266]
Cypher is a declarative graph query language (...) https://en.wikipedia.org/wiki/Cypher_Query_Language

It is a language used by Neo4j and Dgraph will use it. Two very powerful graph databases. How the language is similar to SQL. I think Join-Monster would come in handy.

```sql
 MATCH (start:Content)-[:RELATED_CONTENT]->(content:Content)
    WHERE content.source = 'user'
    OPTIONAL MATCH (content)-[r]-()
    DELETE r, content
```

**Comment by acarl005** [comment]
This would be awesome, but it's out of scope for this project I'm afraid. For this to be possible, Join Monster would need to be advanced enough to abstract away SQL entirely, so that other languages could be placed behind it. This level of abstraction is not possible with JM's architecture.
