### ISSUE TITLE
Multiple columns in where condition

### ISSUE THREAD

**Issue by anuragnagarkota** [join-monster/join-monster#267]
Hey! 
First of all a big thanks for implementing this wonderful package.

I wanted to know whether we could have multiple sql columns in where condition, I have pasted the code from your example. I want to add more columns in this where block. How to achieve this.

 
      where: (usersTable, args, context) => {
        return `${usersTable}.id = ${args.id}`  // here I want to put `${usersTable}.email= ${args.email}` 
      }, 

Thanks in advance

**Comment by stvnmntjy** [comment]
Do you mean something like this?

```js
where: (usersTable, args, context) => {
  const whereClause = [];
  if (args.id) {
    whereClause.push(`${usersTable}.id = ${args.id}`);
  }
  if (args.email) {
    whereClause.push(`${usersTable}.email = ${args.email}`);
  }
  // and so on ...
  return whereClause.join(' AND ');
}
```

**Comment by anuragnagarkota** [comment]
Exactly..thanks
