### ISSUE TITLE
Strange slowness with two fields

### ISSUE THREAD

**Issue by jpincas** [join-monster/join-monster#269]
I wonder if anyone else has come across this strange issue ever.

I have two fields on an object:
```
   players: {
      type: new GraphQLList(Player),
      sqlJoin: (compTable, playerTable) =>
        `${playerTable}.id = ANY (ARRAY(SELECT jsonb_array_elements(${
          compTable
        }.players) ->> 'squadId')::int[])`,
    },
    playerCompDetails: {
      type: new GraphQLList(CompetitionPlayer),
      sqlColumn: 'players',
    },
```

The first is a join on an array I pull out of the json data in 'players', the second is the actual json data in 'players'.

If i have either one of these fields on their own, the query is lightning fast, around 20ms.  If I have them both, it takes several seconds.  I'm a little out of my depth working out what this could be - can anyone offer any advice?

**Comment by wtho** [comment]
I am no performance expert in SQL. I guess `CompetitionPlayer` and `Player` use the same table? Then there might be some side effects when merging the queries for that table. My only idea right now:
* Print the queries before they run against the database (in the callback of `joinMonster(...)`) and run them manually to time the pure DB-query-duration. This way you can see, if it is an issue of the DB (my guess) or Join Monster's pre-/postprocessing

**Comment by nicoabie** [comment]
Closing because this seems to be DB related and JM can't do anything to improve the query performance.
