### ISSUE TITLE
Post-process a type

### ISSUE THREAD

**Issue by entropitor** [join-monster/join-monster#273]
It would be nice of a type would have a post-process function (like the resolve function to post-process fields) to post-process a whole type. 

E.g. in case a certain field of my row has a certain value in the database, I want to modify some other fields (if they are requested)

**Comment by entropitor** [comment]
@acarl005  Do you know if it would be possible to implement this? If so, could you give me some hints as to how I would go about it?

**Comment by nicoabie** [comment]
This seems out of scope of what join monster does. Feel free to come up with an example using https://github.com/join-monster/join-monster-sscce if you think otherwise!
