### ISSUE TITLE
Where condition on type

### ISSUE THREAD

**Issue by VojtaStanek** [join-monster/join-monster#279]
I want to change what user can select based on context (sign-in, role) - as outlined in #45. So I want to specify where condition

Here is how I would like to do it: 
```
where: (table, args, ctx) => {
	return `${table}.${val} = ${ctx.user.id}`
}
```

As I understand it it's not possible, It can be specified on resolver object, not in type.

**Comment by wtho** [comment]
You can create different versions of the `GraphQLSchema`, e. g. not plugging in the mutations in a restrictive one:
```js
function resolveQuery(query, isAdmin) {
  const schema = new GraphQLSchema(isAdmin? permissiveSchemaConfig : restrictiveSchemaConfig)
  return graphql(schema, query)
}
```

**Comment by VojtaStanek** [comment]
@wtho This doesn't solve my use-case, because it might be based e.g. on ownership/relationship with the user. E.g. user can read messages sent to him.

**Comment by wtho** [comment]
@Cactucs Yeah, I had the same issue, I solved it by setting up the context-object before I call `graphql`. In the `where` of the object I then can check for the context object.

The disadvantage is, that I have to use the same context-check everywhere where the object gets joined and in root queries. This is simply an issue graphql itself does not address I guess.
