### ISSUE TITLE
Feature request: Manual offset?

### ISSUE THREAD

**Issue by adampash** [join-monster/join-monster#280]
I've read around the issues and I understand that the join-monster way is to paginate using a relay-compliant spec if you're going to sue JM's `sqlPaginate: true` flag, but I'm wondering: Is there a reason not to allow for a manual offset key the same way that, e.g., `limit` works? E.g.,

```javascript
  // ...
  limit: ({ input: { first = 20 } }) => first,
  offset: ({ input: { offset = 0 } }) => offset,
  // ...
```

If you were amenable to that, I'd be happy to work on a PR to add it.

Thanks,
Adam

Update: Here's a working PR with no test regressions https://github.com/stems/join-monster/pull/281

**Comment by renato** [comment]
I think this feature is essential for non-Relay users.

**Comment by adampash** [comment]
Sorry, I know the maintainers are probably busy, but — does this seem possible? I need to decide if I will need to maintain my own branch or not on this. :/

**Comment by flippidippi** [comment]
I would love this ability for paging with simple GraphQL with Postgres.

**Comment by mposborne** [comment]
I have made a custom MySQL dialect that includes this. Offset is included in my args so does not really require a new node property to be set but you could easily do it this way if you prefer.

Still a work in progress and largely just created for our own project but check it out to see if it will help you.

See: https://github.com/RollHQ/join-monster-mysql

**Comment by GlennMatthys** [comment]
I don't see any reason why this couldn't be included. But before its implementation, please discuss the API as described here: https://github.com/acarl005/join-monster/wiki/Proposal:-manual-OFFSET-LIMIT-control
