### ISSUE TITLE
Non Null Connection Definition

### ISSUE THREAD

**Issue by cliedeman** [join-monster/join-monster#283]
Hello, firstly thanks for the great project.

I often want to enforce that my relay connection nodes are not nullable.

but the following definition 

```
const { connectionType: UserConnection } = connectionDefinitions({
  name: 'ViewerUser',
  nodeType: new GraphQLNonNull(UserType),
  connectionFields: {
    total: { type: GraphQLInt },
  },
});
```

causes the following error.

```Must call joinMonster in a resolver on a field where the type is decorated with "sqlTable". See the error source property for more information.```

I have created PR #282 to fix this

Ciaran

**Comment by bw** [comment]
@cliedeman -- not the owner, but just curious why that's necessary. A properly defined Relay connection should always return `edges` and `total`, should it not? In the case of no results it should in theory return `{ edges: [], total: 0 }`.

**Comment by cliedeman** [comment]
Hello, 

If you take a look at the [swapi](http://graphql.org/swapi-graphql/) films connection you get these definitions

FilmsConnection:
pageInfo: PageInfo!
edges: [FilmsEdge]
totalCount: Int
...

FilmsEdge:
node: Film
...

Only page info is nonnullable. Meaning that even though the join monster implementation will never return null for those fields it's completely legal for the graphql server to do so.
So if you are using flow with relay like I am you have to do a lot of unnecessary null checks.

E.g.

`films && films.edges && films.edges.map(edge => edge && edge.node ) etc.`

The default list implementation is also very relaxed with regard to nulls. E.g.
`new GraphQLList(User);`
means that a list containing null elements is completely legal.
So I usually define my lists as 
`new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(User)));`

Ciaran
