### ISSUE TITLE
Option to query column comments for `description` instead of setting explicitly

### ISSUE THREAD

**Issue by flux627** [join-monster/join-monster#290]
It would be great to set an option to pull from the database for descriptions on databases that support `COMMENT ON ...`.

**Comment by wtho** [comment]
The description it is not a part of the resolved values, but a part of the 'static' GraphQLSchema.

Join Monster does only intercept the resolution of the values by being set as `resolve` method of an object, not the creation of the schema itself, so there is nothing this library can do to help you, you should close this issue.

Still you can implement your feature: The description of `GraphQLObjectType`s is thunked, so you can run a query when the object type gets accessed for the first time:
```js
const MyType = new GraphQLObjectType({
  name: 'MyType',
  description: () => knexOrWhateverDBConnection('QUERY FOR COMMENTS')...
})
```
