### ISSUE TITLE
Concatenate database results

### ISSUE THREAD

**Issue by pedrovinicius** [join-monster/join-monster#291]
Hello!

I'm using `join-monster` in a project of mine, but there is a problem I couldn't figure out its cause up to now. I have 27 databases with the same structure. I need to run a query in all of them and concatenate all the results in one single response. My `resolve` property is like so:

```javascript
  resolve: (parent, args, context, resolveInfo) => {
    return joinMonster(resolveInfo, {}, sql => {
      const pending = Object.keys(databases).map(async (key) => {
        let conn = await databases[key]()
        conn.query = promisify(conn.query)

        return conn.query(sql).then(result => {
          conn.detach()
          return result
        })
      })

      return Promise.all(pending)
        .then(values => [].concat.apply([], values))
        .catch(error => { throw error })
    })
```

`databases` is an object in that each key represents a database connection. As you can see, I'm executing the same query in all databases. All the results are being returned pretty well. But when I execute a GraphQL query, the following result is being returned:

```json
{
  "data": {
    "offices": [
      {
        "id": "21300380",
        "name": "Portela Lima e Colen Advogados",
        "address": null,
        "city": null,
        "state": null,
        "clients": [
          {
            "clientcode": "COLIN301",
            "email": "controladoria@plcadvogados.com.br"
          }
        ]
      }
    ]
  }
}
```

In my database, the office `21300380` has at least 300 clients, but in the GraphQL response, a single client is being returned. What am I doing wrong here?

**Comment by wtho** [comment]
This doesn't seem like an issue with JoinMonster, better ask this on SO.

You should check the data structure that gets returned to join monster. You can do that using a node debugger or adding `.then(res => { console.log(res); return res })` at the end of the chain.

Also the mix of `.then` and `await` seems a bit confusing to me, I would recommend you to try to keep your code more understandable using only one of the two techniques.

The issue with just displaying one item sounds more like a problem with `uniqueId`. JoinMonster takes it very serious to differentiate between objects using their unique id.

**Comment by GlennMatthys** [comment]
Interesting. As @wtho mentioned, check the returned data structure and the key must absolutely be unique for every record returned. If you cannot guarantee this uniqueness across your databases, the easiest way out would be to prefix the ID's being returned with something specific to that database, perhaps:

```
fields:
{
    id:
    {
        sqlExpr: (table) => `CONCAT(some_differentiator_here_maybe_hostname, ${table}.id)` 
    }
}
```

Other than that, this should just work with Join Monster. If you're still having problems and you've ruled out these two points, feel free to re-open this issue.
