### ISSUE TITLE
Need to access parent args in child property where-function 

### ISSUE THREAD

**Issue by fhollste** [join-monster/join-monster#294]
Background:
I use a custom function for generating prepared SQL statements based on user arguments. This works fine in the parent resolver except for cases where there are separate queries as a result of `sqlBatch`. 

Issue: 
a) The main/parent resolver does not receive the tablename of the batched query.
b) the where-function does not have access to the parent args

Question:
Any way to access parent args in the where-function without adding the parent's args to the property itself?

**Comment by wtho** [comment]
The fourth argument of the where-function is the `sqlASTNode`, which contains all information to build the query. The `sqlASTNode` is build in a hierarchy similar to the GraphQL query, and it also contains the arguments of a node. Furthermore it contains the parent's `sqlASTNode`. To access the parent's arguments you can do the following:
```js
someField: {
  ...
  where: (table, args, ctx, sqlASTNode) => {
    const parentArg = sqlASTNode.parent.args.parentArgumentName
    ...
  }
}
```
I have not tried this with `sqlBatch`, but it should work, as the `sqlASTNode`s are constructed, before the queries are run.

Please close this issue, if this solved your problem.

**Comment by fhollste** [comment]
Thanks for the tip, that does work but only if the parent is bound to a SQL table.
I am using a query like this:
```
{
  parentquery(limit: 99, offset: 0, filters: [{...}]) {
    property1 {
      id
    }
    property2 {
      id
      child {  // this uses a sqlBatch
        id
        ...
      }
    }
  }
}
```
where `property1`, `property2` and `child` are used to fetch data from SQL with joinMonster. `parentquery` is not bound to a SQL table. In this case `sqlASTNode` of eg. `property2` does not have a `parent` property. The `where` function would need to access either the root args of the query or `resolveInfo.variableValues`. Any way of achieving this (without copying the arguments to all sub-properties in the query)?

**Comment by wtho** [comment]
Yeah, I see what you mean now. When the resolve-function of `property` is called, you cannot access the parent's variable. But Join Monster does not kick in till the arguments are gone, so it anyway has no chance of helping you here, Graphql seems to be very strict about argument visibility.

I think for these cases Graphql gives you the possibility to stuff information in the context object:
* In the `parentquery`'s resolver, set the arguments somewhere in the context object or make sure it is empty, if not set.
* Now the child-properties can access it.
It has to be cleared by the `parentquery` to avoid a scenario like this:
```
{
  q1: parentquery(...) { property1 { ... } ... }
  q2: parentquery { property1 { ... } ... }
```
If not reset, the children of `q2` will access the same arguments from the context as in `q1`

This option is nice, as you even get the context object in the `where` function, and can easily add conditions to the SQL statement. What do you think?

**Comment by fhollste** [comment]
I see. I was thinking that might be the case. 
I already implemented setting the arguments in the context and it worked fine for client side requests. However when rendering a page server-side with multiple queries there is only one context for all queries (the app is isomorphic). One possible solution here would be to create some id for each query to separate the arguments.
Although not pretty, I think the most logical/robust solution is to pass down the arguments in the query itself. Thanks for the input!
