### ISSUE TITLE
Use the API to generate SQL from GraphQL in a web browser?

### ISSUE THREAD

**Issue by sebastianmacias** [join-monster/join-monster#297]
Can join-monster be used as a library on a web browser to generate SQL without having to run a server?

Thanks

**Comment by sebastianmacias** [comment]
To clarify why I would need this. I'm planning on using it with [sql.js](https://github.com/kripken/sql.js)

**Comment by wtho** [comment]
I am not the maintainer or a collaborator, but I see no issue with using it in the browser. I just think the overhead using GraphQL + Join Monster to auto-build some queries is too much, but I guess it should work.

**Comment by sebastianmacias** [comment]
Thanks for your comment @wtho. I want to run some tests and see. I think the overhead might be offset by having a single user / dedicated local database on the client instead of having to make requests to a remote server.

**Comment by GlennMatthys** [comment]
Can? Yes. Should you? Not sure. Your query builder would be limited to what your GraphQL schema offers and Join monster's capabilities, which is only a small subset of SQL. Though running in the browser is not the primary use case of this library, if you have any problems running it in a browser, you can consider it a bug, report it as such and we will try to fix it.
