### ISSUE TITLE
Postgres limit/offset

### ISSUE THREAD

**Issue by flippidippi** [join-monster/join-monster#300]
Is there a reason why I get "This type of pagination not supported on this dialect" when trying to use limit for Postgres? Seems like Postgres should support this as it does have OFFSET and LIMIT. 

If they can be supported, it would be nice to also have offset for Postgres according to this issue https://github.com/stems/join-monster/issues/280.

**Comment by mposborne** [comment]
I have made a custom MySQL dialect that includes this. Offset is included in my args so does not really require a new node property to be set but you could easily do it this way if you prefer.

Still a work in progress and largely just created for our own project but check it out to see if it will help you. I'm sure PG format will be largely the same.

See: https://github.com/RollHQ/join-monster-mysql

**Comment by zachrdz** [comment]
> I have made a custom MySQL dialect that includes this. Offset is included in my args so does not really require a new node property to be set but you could easily do it this way if you prefer.
> 
> Still a work in progress and largely just created for our own project but check it out to see if it will help you. I'm sure PG format will be largely the same.
> 
> See: https://github.com/RollHQ/join-monster-mysql

I know this is kind of an old post, but I just started using join-monster and wanted to say that this solution worked for me! I'm using as Postgres database and was having the same issue with limit throwing the error mentioned above.

I was able to use the mysql dialect you provided in your link. I just had to change line 14 from `name: 'mysql'` to `name: 'pg'`, as well as adjust the quote function to use double quotes instead of back ticks like this:
```
function quote(str) {
    return `"${str}"`;
}
```
Edit: I also updated the return value of the `offsetPagingSelect` function, since it was throwing a `$total` is not defined error.
```
return `\
          FROM (
            SELECT DISTINCT ${q(as)}.*, count(*) OVER () AS "$total"
            FROM ${table} ${q(as)} ${joins}
            WHERE ${whereCondition}
            ORDER BY ${dialect.orderColumnsToString(order.columns, q, order.table)}
            LIMIT ${limit} OFFSET ${offset}
          ) ${q(as)}`;
```

Finally, I imported and used the dialect as suggested and it works like a charm.
```
const dialect = require('../postgres.dialect');
...
...
users: {
        type: new GraphQLList(User),
        args: {
            isActive: { type: GraphQLBoolean },
            limit: { type: GraphQLInt }
        },
        orderBy: { lastName: 'asc' },
        limit: args => (args.limit && args.limit < 100) ? args.limit : 100,
        where: (usersTable, args, context) => isBoolean(args.isActive)
            ? `${usersTable}."isActive" = ${args.isActive}`
            : null,
        resolve: (parent, args, context, resolveInfo) => joinMonster(
            resolveInfo, {}, sql => pgdb.query(sql), { dialectModule: dialect }
        )
    }
...
```

**Comment by CassianoSF** [comment]
I had the same problem with oracle, find a work arround based on @zachrdz comment.

I just imported the dialect form joinMonster node_module

```js
import oracleDialect from '../../node_modules/join-monster/dist/stringifiers/dialects/oracle'
```

and use it as dialectModule inside the resolver:

```js
...
      resolve: (parent, args, context, resolveInfo) => {
        return joinMonster(resolveInfo, { dialect: 'oracle' }, (sql) => {
          return db.raw(sql)
        }, {
          dialectModule: oracleDialect
        })
      }
...
```
EDIT:

The `{ dialect: 'oracle' }` is also necessary.
