### ISSUE TITLE
Getting `noop` when trying to limit a join and return a built-in type

### ISSUE THREAD

**Issue by bennettrogers** [join-monster/join-monster#302]
I'm trying to do something similar to #106, but with a slight twist. I'd like to JOIN a related table that has a timestamp field, and return the most recent timestamp as a GraphQLString. I've tried the correlated subquery approach, but I keep getting a `noop` in the result when looking at the join-monster debug output. I think the problem may be that the field needs to return a GraphQLString, and not one of my custom types that are related to a sqlTable. Looking at the schema-basic example, I see this in the User type:

> // object types without a `sqlTable` are a no-op. Join Monster will ignore it and let you resolve it another way!

What is the correct way to join 2 tables and return a (single) default scalar type from the 2nd table? (Current failing approach shown in the firstTimestamp field below.)

<details>
  <summary>Details (simplified)</summary>

<h3>Frame type</h3>
<pre>
const Frame = new GraphQLObjectType({
  name: "Frame",
  sqlTable: "frame",
  uniqueKey: "id",
  fields: () => ({
    timestamp: {
      type: new GraphQLNonNull(GraphQLString),
      sqlColumn: "timestamp",
      resolve: frame => {
        return moment(frame.timestamp).unix();
      }
    }
  })
});
</pre>

<h3>Series type</h3>
<pre>
const Series = new GraphQLObjectType({
  name: "Series",
  sqlTable: "series",
  uniqueKey: "id",
  fields: () => ({
    id: {
      type: new GraphQLNonNull(GraphQLString),
      sqlColumn: "id"
    },
    name: {
      type: new GraphQLNonNull(GraphQLString),
      sqlColumn: "name"
    },    
    firstTimestamp: {
      type: GraphQLString,
      sqlJoin: (seriesTable, frameTable) =>
        // How do I return a single timestamp string here?
        `${seriesTable}.id = (select id, timestamp from ${frameTable} where ${frameTable}.series_id = ${seriesTable}.id order by timestamp desc limit 1)`
    }
  })
});
</pre>

<h3>Frame table</h3>
<pre>
                                    Table "public.frame"
      Column       |            Type             | Collation | Nullable |      Default
-------------------+-----------------------------+-----------+----------+-------------------
 id                | uuid                        |           | not null | gen_random_uuid()
 series_id         | uuid                        |           | not null |
 timestamp         | timestamp without time zone |           | not null |
Indexes:
    "frame_pkey" PRIMARY KEY, btree (id, "timestamp")
    "ix_frame_series_id" btree (series_id)
Foreign-key constraints:
    "frame_series_id_fkey" FOREIGN KEY (series_id) REFERENCES series(id)
</pre>

<h3>Series table</h3>
<pre>
                          Table "public.series"
  Column  |       Type        | Collation | Nullable |      Default
----------+-------------------+-----------+----------+-------------------
 id       | uuid              |           | not null | gen_random_uuid()
 name     | character varying |           | not null |
Indexes:
    "series_pkey" PRIMARY KEY, btree (id)
</pre>

</details>

**Comment by nicoabie** [comment]
Please provide a https://github.com/join-monster/join-monster-sscce
