### ISSUE TITLE
3 SQL joins?

### ISSUE THREAD

**Issue by leonschwanitz** [join-monster/join-monster#307]
SQL Table:
[users] [user_documents] [documents]

How can I make an SQL join in all these tables?

The GraphQL Schema looks like:
```
user(id: 1) {
    fullName
    documents {
        fileName
    }
}
```

**Comment by dhenson02** [comment]
Use the **junction** feature.  It would look something like this for you as a "document" field using a custom "documentType" (that is assigned `sqlTable: 'documents'`) inside your parent "user" type:

```javascript
    // ...
    'documents': {
        'type': new GraphQLList(documentType),
        'junction': {
            'sqlTable': `user_documents`,
            'sqlJoins': [
                ( parentTable, junctionTable ) => `${parentTable}.id = ${junctionTable}.user_id`,
                ( junctionTable, targetTable ) => `${junctionTable}.document_id = ${targetTable}.id`
            ]
        }
    },
```
...adjusting names of `id` columns to fit your setup (`document_id` and `user_id` are my assumptions).

[Here is the full documentation](http://join-monster.readthedocs.io/en/latest/many-to-many/)
