### ISSUE TITLE
Is it possible to retrieve users that wrote comments in {year} ?

### ISSUE THREAD

**Issue by doei** [join-monster/join-monster#309]
Thanks for join-monster, great approach to a difficult problem !

I wanted to know if it's possible to add a condition that refers to another table, basically:
```sql
SELECT DISTINCT * from users u
JOIN comments c ON c.user_id = u.id
WHERE c.year = 2018
```

I'd like to be able to  send the `year` in the graphql query here, which would look something like:
```graphql
users(wroteCommentInYear: 2018){
	id
	name
}
```

In summary I'd like to be able to query my server with what could be translated as "Give me all users that wrote comments in 2018".

Thanks for the help :)

**Comment by acarl005** [comment]
You can add that condition inside the `JOIN` condition

```sql
SELECT DISTINCT * from users u
JOIN comments c ON c.user_id = u.id AND c.year = 2018
```
