### ISSUE TITLE
Add args to joinMonster function similar to context

### ISSUE THREAD

**Issue by flippidippi** [join-monster/join-monster#310]
There are instances where we would like to change the args passed in before calling` joinMonster` so the where clause gets the correct args. Stuff like changing an argument to match something in context, pre-esacping/trimming args etc.

`joinMonster(resolveInfo, args, context, sql => { return knex.raw(sql) }`

This would allow for better separation of duties. Currently we have to perform these things in the where clause itself or attach the cleaned up args in `context`, which really isn't a smooth way.

**Comment by GlennMatthys** [comment]
Perhaps wrap joinMonster like [described here](https://github.com/acarl005/join-monster/issues/224#issuecomment-435491183)?

**Comment by flippidippi** [comment]
We ended up righting a function similar to `combineResolvers` from https://github.com/lucasconstantino/graphql-resolvers so we can just wrap any where clause and change the args before continuing. Similar to what's described there just a little more plug and play.

```js
// Alters function arguments by passing them down each time
// It's like piping but for arguments instead of results
// Each function should have the same argument list and return array of arguments for the next
const alterArguments = (...funcs) => (...args) => funcs.reduce(
  (prevPromise, resolver) => prevPromise.then(
    nextArgs => {
      return resolver(...nextArgs)
    }
  ), Promise.resolve(args)
)
```

You can use it like:

```js
function cleanupWhereUsers (table, args, context) {
  const newArgs = { ...args }
  newArgs.search = newArgs.search.trim()

  return [table, newArgs, context]
}

const metadata = {
  Query: {
    fields: {
      users: {
        where: alterArguments(
          cleanupWhereUser,
          (table, args, context) => { ... }
       )
    }
  }
}
```
