### ISSUE TITLE
Update Graphql Dep

### ISSUE THREAD

**Issue by chaffeqa** [join-monster/join-monster#315]
Latest graphql is 0.13.2, could you try updating the peer deps and see if it just works?

Currently breaks since you cannot use x2 different graphql versions at the same time 😢

**Comment by ghost** [comment]
Stem could use a graphql ^0.13 dependency, too.  I just updated @stem/koa-graphql while fixing old dependencies, but now I'm getting warnings from a mismatched peer dependency on graphql.  Is there any reason to think this wouldn't be compatible with 0.13.x?

**Comment by GlennMatthys** [comment]
package.json has graphql 0.13 as peer dependency, so when you're pulling in peer dependencies it should pull in 0.13.2. Is it not working for you?

**Comment by lorensr** [comment]
`join-monster@2.1.2` had:

```json
  "peerDependencies": {
    "graphql": "0.6 || 0.7 || 0.8 || 0.9 || 0.10 || 0.11 || 0.12 || 0.13"
  },
```

`join-monster@3.0.0-alpha.1`'s peer dep is `graphql@^15.2.0`.
