### ISSUE TITLE
[PG] sqlBatch with limit on BigInt values: "operator does not exist: bigint = text"

### ISSUE THREAD

**Issue by matthewgonzalez** [join-monster/join-monster#316]
_Using Postgres 9.4.15, `join-monster` v.2.0.16 using `pg` dialect, `pg-promise`/`node-postgres`._

It appears that in the process of generating the second SQL query in a batch with a limit in place, that BIGINT values from first query are translated as strings in Javascript and thus are not able to be operated against subsequent BIGINT's.

**Error:** `operator does not exist: bigint = text`

**Example Object:**
```javascript
const User = new GraphQLObjectType({
  name: 'User',
  sqlTable: 'user',
  uniqueKey: 'id',
  fields: () => ({
    comments: {
      type: new GraphQLList(Comment),
      orderBy: 'id',
      limit: 5,
      sqlBatch: {
        thisKey: 'user_id', // <-- BIGINT
        parentKey: 'id', // <-- BIGINT
      },
    },
  }),
})
```

**Example Generated SQL:**

[...]

```sql
FROM (VALUES ('1234'),('1235'),('1236'),('1237')) temp("id") 
JOIN LATERAL ( ... 
```

[...]

```sql
LIMIT 5 OFFSET 0
) "comment$" ON "comment$"."user_id" = temp."id"
```

Notice that the BIGINT `id`'s (1234, 1235, etc.) have been converted to strings and thus will throw an error when operated against `"user$"."user_id"`

**Expected:** Operating on two BIGINT's should not cause an operator error.

**Comment by matthewgonzalez** [comment]
BTW, `node-postgres` automatically converts BIGINT to strings. This is what is causing the `temp."id"`'s in the example above to be rendered as such. Since `"comment$"."user_id"` hasn't been translated through JS, it remains a BIGINT.

To get this to work with `join-monster` I need to add the following `node-postgres` config to translate BIGINTs to integers. 
```javascript
pgp.pg.types.setTypeParser(20, (value) => {
  return parseInt(value);
});
```

I still think that `join-monster` should handle this more gracefully. 

Perhaps it can check what the `temp."id"` type is before creating the second query and then cast that type onto the key it is being operated against.

e.g.: 
```javascript
"comment$"."user_id"::TEXT = temp."id"
````

**Comment by theogravity** [comment]
I also have this problem with the uuid col type at times as well... unsure how a fix for that one would work

**Comment by matthewgonzalez** [comment]
My PR would likely fix that if you are running into the problem during `sqlBatch`'es. 

For the time being, I don't know of a simple workaround for this since `uuid` type has both numbers and letters and cannot be translated into JS land in any other way besides a string.

**Comment by theogravity** [comment]
The uuid type is stored in postgres as binary from my understanding, and is serialized out as text. Definitely would be an issue since you wouldn't be able to tell the original type since it would be a string in JS land as you've stated.
