### ISSUE TITLE
where clause on a junction table causes parent types that wrap it not to resolve. 

### ISSUE THREAD

**Issue by velevtzvetlin** [join-monster/join-monster#317]
I am getting an array of templates with a type on templates that also should return an array that goes through a junction table. If I add the where clause on the junction, i lose templates for some reason which to me makes no sense because template is a parent type.

**Comment by acarl005** [comment]
This is counter-intuitive, but intended behavior. When you use the `WHERE` clause it will follow the semantics of SQL. If you want to keep the parent, you can add the condition to the `LEFT JOIN` instead.

Something like `LEFT JOIN child ON child.parent_id = parent.id AND child.attribute = 'some_value'` to get the semantics you expect.
