### ISSUE TITLE
More robust stripRelayConnection

### ISSUE THREAD

**Issue by mnpenner** [join-monster/join-monster#336]
`stripRelayConnection` is defined as:

```
function stripRelayConnection(gqlType, queryASTNode, fragments) {
  const strippedType = gqlType._fields.edges.type.ofType._fields.node.type;
  ...
```

Which is fine if you implement the Relay spec *exactly* but if your edges are non-nullable (and I'm not sure why they wouldn't be, but I'm new to this), then the above expression errors out.

i.e., this is allowed:

```
interface RelayConnection {
	edges: [RelayEdge]  
	pageInfo: PageInfo!
}
```

But this craps out:

```
interface RelayConnection {
	edges: [RelayEdge!]! # <-- a non-null array of non-null edges
	pageInfo: PageInfo!
}
```

The `!`/`GraphQLNonNull` adds a few extra levels to the `gqlType` which should be unwrapped.

-----

Same for edges:

```
type BranchEdge implements RelayEdge {
	cursor: Cursor!
	node: Branch # <-- cannot put ! here
}
```

**Comment by cliedeman** [comment]
Does this [commit](https://github.com/acarl005/join-monster/commit/4d2f1f75204b64e7a2a3ca1f7f31e8e972f4a04d) help?

**Comment by mnpenner** [comment]
@cliedeman Yeah, that looks like it will do what I wanted it to do. Thanks!
