### ISSUE TITLE
Typescript Definitions are not published

### ISSUE THREAD

**Issue by danielberndt** [join-monster/join-monster#340]
Hi there, it seems like the `index.d.ts` is [not being published](https://unpkg.com/join-monster@2.0.16/) to npm.

**Comment by wtho** [comment]
You are right, the current github master is not published yet. The last publish happened on October 3rd 2017.

You can request the owner to publish a new version and till then
* add the types on your own using [declare module](https://www.typescriptlang.org/docs/handbook/modules.html#working-with-other-javascript-libraries) or
* fork the repo, build it, commit the `dist` folder and use `npm i githubusername/join-monster#branch-with-dist` or
* work with a local copy of the repository and reference it using `"join-monster": "file:../path/to/lib"`

**Comment by acarl005** [comment]
They should be published now in `2.1.0`.
