### ISSUE TITLE
Ambiguous Table Alias

### ISSUE THREAD

**Issue by Southporter** [join-monster/join-monster#344]
Sqlite3 is throwing this error: `Error ambiguous column name: informatio.id`

I'm dealing with a table "InformationItem" and a many-to-many table called "InformationItemHasGroup". Join Monster creates the aliases "informatio" and "Informatio" respectively.
Sqlite3 is case INsensitive when it comes to resolving aliases. Thus `informatio` and `Informatio` are equivalent in Sqlite3, causing the error.

Is there a way around this that I haven't found in the docs?

As I see it, there are either two ways of dealing with this. Either changing the alias scheme to not use capitalization as a way of generating a unique alias, or allow an field attribute of `alias` that can be specified by the user.

**Comment by GlennMatthys** [comment]
Can you submit a database schema and some code that produces this error?

**Comment by nicoabie** [comment]
Please provide running example using https://github.com/join-monster/join-monster-sscce

**Comment by Southporter** [comment]
Sorry, it's been too long. I don't have the original code/issue for this. Closing this issue.

**Comment by nicoabie** [comment]
Latest version does not have that issue anymore, I added a test to make sure it does not happen again
