### ISSUE TITLE
Is this library dead?

### ISSUE THREAD

**Issue by irakli-lekishvili** [join-monster/join-monster#351]
This library looks so awesome, but unfortunately I can't use with latest(`14.0.2`) GraphQL. I get this error: `"message": "Cannot read property 'sqlTable' of undefined"`.

Is this library dead?

To reproduce just update GraphQL dependency version to `14.0.2` in the [example project](https://github.com/stems/join-monster-demo).

**Comment by naturalethic** [comment]
Temporary work-around described here https://github.com/acarl005/join-monster/issues/352#issuecomment-423923011

**Comment by RedShift1** [comment]
They really shouldn't have taken away this functionality before providing an alternative.

**Comment by acarl005** [comment]
Nope, not dead. Just in the (slow) process of appointing a new maintainer.

**Comment by namse** [comment]
Can we check how that process is going on?

**Comment by namnm** [comment]
Let's make it happen

**Comment by upasanadash** [comment]
You can use like this:
      objectTypeName._typeConfig = {
        sqlTable: "tablename",
        uniqueKey: 'id'

Here objectTypeName is the types of your object type. Like:

const Films =  new GraphQLObjectType({
.....
.....
})

Here Films is an object type.

sqlTable is 
table name

Hope this is helpfull

**Comment by tslater** [comment]
Is there a new maintainer selected? or is the current maintainer looking?

**Comment by jeveloper** [comment]
Hey Friends, wonder what is happening with this lib? I use oracle and there aren't many options

**Comment by namnm** [comment]
Well, nothing is happening with this lib 😅
Most of people here use postgres or mysql, sorry to see your oracle 😅

**Comment by jeveloper** [comment]
@namnm  guessing you're an amateur developer that only knows of pg and mysql.

**Comment by namnm** [comment]
Hey, judging other people doesnt make you better. If you are a pro, why dont you fork this lib and contribute on it for the community?
You make me laugh very hard 😂Thank you 😂

**Comment by jeveloper** [comment]
@namnm  dude, you're the one making fun of others.

**Comment by namnm** [comment]
I have used mongodb, oracle, ms sql, mysql, postgre in my career. In conclusion your guess is wrong.
Let's stop here and keep the correct discussion about this library.
Have a nice day.

**Comment by namse** [comment]
Stop fight here.

**Comment by katywings** [comment]
About forking: it would be interesting how many peeps would be interested in contributing into a fork

**Comment by biels** [comment]
@katywings I am interested!

**Comment by lorensr** [comment]
We're forming a team to maintain—check out #399 if you're interested! cc @katywings @biels

**Comment by lorensr** [comment]
Closing this issue in favor of #352, which has more details on the `Cannot read property 'sqlTable' of undefined` error
