### ISSUE TITLE
Problems on using with AWS AppSync

### ISSUE THREAD

**Issue by patrickyau-visualsquares** [join-monster/join-monster#353]
Hello all, I am pretty new to GraphQL and all related stuff. Sorry if I am asking something duplicated or stupid. I can't find any related resource on working on join-monster with AWS AppSync.

I am playing around with AWS AppSync, using their query dashboard with the following query:

```graphql
{ 
  getPosts {
    items {
      id
      title
    }
  }
}
```
It becomes a JSON like:

```json
{
    "arguments": {},
    "identity": {
      ...
    },
    "source": null,
    "result": null,
    "request": {
      ...
    },
    "error": null,
    "outErrors": []
}
```
It doesn't look like a normal "query string" used in any of the join-monster examples.
Can anyone give me some pointer?

Thanks to all of you.

**Comment by RedShift1** [comment]
This sounds like something specific to AWS AppSync and not related to join monster.

**Comment by patrickyau-visualsquares** [comment]
thanks for the information, closing this as this is not related.
