### ISSUE TITLE
Field authorization error

### ISSUE THREAD

**Issue by flippidippi** [join-monster/join-monster#361]
I have an issue with authorization when trying to authorize more than one sqlJoin. For example if I do

```
Parent: {
  subField1: {
    resolve: authSubField1
  },
  subField2: {
    resolve: authSubField2
  }
}
```

With query
```
{
  parent {
    subField1 {
        ...
    }
    subField2 {
        ...
    }
  }
}
```

If authSubField1 throws an error for not authorized, then in errors I get the correct message like Unauthorized/Forbidden.

However if authSubField2 throws an error, then I get something like Cannot return null for non-nullable field Parent.subField1.

I'm guess it's something weird with the ordering, and how the errors are handled with multiple sqlJoins?

**Comment by nicoabie** [comment]
Please provide running example using https://github.com/join-monster/join-monster-sscce
