### ISSUE TITLE
Which one is better dataloader or join monster?

### ISSUE THREAD

**Issue by upasanadash** [join-monster/join-monster#369]
I am working on GraphQL. For SQL which one is better join monster or data loader?

**Comment by Felix-N** [comment]
I can only tell you from my perspective:

I've used joinmonster and switched over to Datalader.

Following reasons:
1. Activity. Joinmonster feels like a dead lib
2. Bus. Joinmonster has a strange big resulting in won't data fetching when using batching.
3. Control. Dataloader gives me more control, it's not that i missed anything in joinmonster, but it feels clearer in the code using dataloader.
4. Memory. Big joins in joinmonster resulted in out of memory problems. Batching helped here, but the above mentioned bug...

However joinmonster is faster as less round-trips are needed to the db, at least in my case with quite some depth traversal. That said the speed difference is not hughe and i could probably work around it.

**Comment by upasanadash** [comment]
Thank you so much. It is very helpful

**Comment by namnm** [comment]
I really like the idea and how this library works, feel like perfect! There's an opening issue that finding new maintainers for this project: https://github.com/acarl005/join-monster/issues/351 Any one of you interest?

**Comment by nicoabie** [comment]
I'm a new maintainer and I'll try to prevent it from dying!

Cheers!
