### ISSUE TITLE
join monster aggregate function

### ISSUE THREAD

**Issue by upasanadash** [join-monster/join-monster#371]
How to use a join monster count function using node with graphql?

It is showing an error 

If an Object type maps to a SQL table and has a child which is another Object type that also maps to a SQL table,\n        you must define \"sqlJoin\", \"sqlBatch\", or \"junction\" on that field to tell joinMonster how to fetch it

**Comment by gregbelyea71** [comment]
What does your code look like... sounds to me like you specified a field that is actually another object in your schema but you did not give joinMonster enough data about it.. Say a Post would have a comment associated in your schema... well same thing in join-monster like follows

`           comments: {
                sqlJoin: (postTable, commentTable) => `${postTable}.POST_ID = ${commentTable}.POST_ID`, 
            },
`

**Comment by nicoabie** [comment]
Closing because of lack of info. File a https://github.com/join-monster/join-monster-sscce to show the error.
