### ISSUE TITLE
Is there a reason not to release for a long time?

### ISSUE THREAD

**Issue by kishmiryan-karlen** [join-monster/join-monster#385]
Hello,

I've started to use join-monster in one of projects a couple of months ago. Today I decided to check its repo again and noticed that the last commit on `master` was on **July 4th**, however your latest release (_2.0.15_) was on **Oct 3, 2017**.

I wonder, why did you stop releasing new versions 2 years ago? 
Does that mean you are going to have a big release soon?

**Comment by tonypee** [comment]
I interested in this too, this project seems great. But it seems that @acarl005 has stopped contributing very much. Is there a plan going forward for maintenance/releases?

**Comment by esatterwhite** [comment]
@acarl005 I'm pretty sure this doesn't work with the most recent version (v14) of graphqljs.
It doesn't keep a reference to the the config passed to the scalar constructor in `_typeConfig`
https://github.com/graphql/graphql-js/blob/v14.0.0/src/type/definition.js#L636-L643

which join-monster is trying to introspect
https://github.com/acarl005/join-monster/blob/master/src/index.js#L132

**Comment by esatterwhite** [comment]
https://github.com/graphql/graphql-js/pull/1417

**Comment by lorensr** [comment]
We're creating a team to maintain—see #399

@esatterwhite  You're correct—that's tracked in #352.
