### ISSUE TITLE
Custom MySQL Dialect for limit

### ISSUE THREAD

**Issue by ICPaulCotterellI** [join-monster/join-monster#389]
I am developing a custom mysql dialect module to handle limit functionality in the generated sql statement.

When I pass across a function to the "limit" property, this function is resolved in the SQL AST process which sets the "limit" property as the value returned by the function.

However, I am looking to return a promise from the "limit" property which would allow me to dynamically limit the sql statement.

First question. I would like to stop the SQL AST process from resolving the "limit" function, so I can handle the limit function manually in my custom mysql dialect module. Where is the code that does this?

Second question. Another solution would be to pass across a new property, rather than "limit", which I can handle. For example, I have added "limitOffset" below:

`applications: {

               type: new GraphQLList(IDealApplications),
                sqlBatch: {
                    thisKey: 'ideal_ID',
                    parentKey: 'ideal_ID'
                },
                orderBy: {id: 'asc'},
                limitOffset: () => Promise.resolve(3)
            }`

However, the custom property "limitOffset" gets removed from the SQL AST object.

How can I indicate to join monster that "limitOffset" is a valid property and shouldn't be removed?

Thanks
Paul

**Comment by nicoabie** [comment]
See https://github.com/join-monster/join-monster/issues/243
