### ISSUE TITLE
Backwards pagination with offsets

### ISSUE THREAD

**Issue by kukagg** [join-monster/join-monster#391]
It looks like this check for backwards pagination support doesn’t check for possibility of `last` and `before` fields even though it works fine.

L99 in `/src/stringifiers/shared.js`: https://github.com/acarl005/join-monster/blob/master/src/stringifiers/shared.js#L99.

Thoughts?

**Issue**

Query like `{ users(after: cursor, first: 4) }` works fine but `{ users(before: cursor, last: 4) }` doesn’t.

**Solution**

```js
  if (idx(node, _ => _.args.last) && !idx(node, _ => _.args.before)) {
    throw new Error('Backward pagination not supported with offsets. Consider using keyset pagination instead')
  }
````

What am I missing?

**Comment by nicoabie** [comment]
New maintainer here, can you file a https://github.com/join-monster/join-monster-sscce ?
