### ISSUE TITLE
Composite uniquekey: operator does not exist: integer || integer

### ISSUE THREAD

**Issue by eae710** [join-monster/join-monster#392]
I have a composite unique key with two fields in postgres.
In simple query in graphQL throw me this error:

"errors": [
        {
            "message": "operator does not exist: integer || integer",
            "locations": [
                {
                    "line": 1,
                    "column": 3
                }
            ],
            "path": [
                "bienesSubrubros"
            ]
        }
    ]

The generated query is:
 SELECT  "bienesSubr"."idrubro" || "bienesSubr"."idsubrubro" AS "idr#ids" FROM my_table

Definition Type:

var BienesSubrubrosType = new GraphQLObjectType({
    name: 'BienesSubrubros',
    fields: () => ({
        idrubro: { type: GraphQLInt },
        idsubrubro: { type: GraphQLInt },
        descripcion: { type: GraphQLString }
    })
})

BienesSubrubrosType._typeConfig = {
    sqlTable: 'my_table',
    uniqueKey: ['idrubro', 'idsubrubro', 'descripcion']
}

**Comment by iltommi1995** [comment]
I have got the same error, any news?

**Comment by Allan-Nava** [comment]
> I have got the same error, any news?

Me too!

**Comment by ilmaria33** [comment]
> I have got the same error, any news?

Same here, I've tried multiple times but without any success. Is there any workaround for this?

**Comment by matthew-plusprogramming** [comment]
@lorensr I have been following issue #352 for a while, and saw your update 24 days ago. Although this issue is old, I think this error is related to the 3.0.0-alpha1 update to join-monster.

**Comment by lorensr** [comment]
You're seeing this with `3.0.0-alpha1`? Can you provide a repro?

**Comment by matthew-plusprogramming** [comment]
Unfortunately, I'm working on code for my job (partially covered under NDA) using join-monster. However, I can give this code snippet which is supposed to create a many to many batch relation between two tables. 

Note: The code of interest is the `items` field in the Plan Object
```javascript
const Plan = new graphql.GraphQLObjectType({
  name: 'Plan',
  extensions: {
    joinMonster: {
      sqlTable: 'plans',
      uniqueKey: 'id',
    },
  },
  fields: () => ({
    id: { type: graphql.GraphQLID },
    title: { type: graphql.GraphQLString },
    subtitle: { type: graphql.GraphQLString },
    start_date: { sqlColumn: 'start_date', type: graphql.GraphQLString },
    end_date: { sqlColumn: 'end_date', type: graphql.GraphQLString },
    //vvv This field is causing the 'operator does not exist: integer || integer' error in GraphiQL
    items: {
      type: graphql.GraphQLList(Item),
      extensions: {
        joinMonster: {
          junction: {
            sqlTable: 'item_assignments',
            uniqueKey: ['item_id', 'plan_id'],
            sqlBatch: {
              thisKey: 'plan_id',
              parentKey: 'id',
              sqlJoin: (junctionTable, planTable) =>
                `${junctionTable}.item_id = ${planTable}.id`,
            },
          },
        },
      },
    },
  }),
});
```
Some supplemental info:
* I do have a "twin" junction on the other GQLObject (Item) to complete the many to many relationship
* All of the tables are setup correctly (in accordance to the metadata given to join-monster) in the Postgres DB

**Comment by Allan-Nava** [comment]
> Unfortunately, I'm working on code for my job (partially covered under NDA) using join-monster. However, I can give this code snippet which is supposed to create a many to many batch relation between two tables.
> 
> Note: The code of interest is the `items` field in the Plan Object
> 
> ```js
> const Plan = new graphql.GraphQLObjectType({
>   name: 'Plan',
>   extensions: {
>     joinMonster: {
>       sqlTable: 'plans',
>       uniqueKey: 'id',
>     },
>   },
>   fields: () => ({
>     id: { type: graphql.GraphQLID },
>     title: { type: graphql.GraphQLString },
>     subtitle: { type: graphql.GraphQLString },
>     start_date: { sqlColumn: 'start_date', type: graphql.GraphQLString },
>     end_date: { sqlColumn: 'end_date', type: graphql.GraphQLString },
>     //vvv This field is causing the 'operator does not exist: integer || integer' error in GraphiQL
>     items: {
>       type: graphql.GraphQLList(Item),
>       extensions: {
>         joinMonster: {
>           junction: {
>             sqlTable: 'item_assignments',
>             uniqueKey: ['item_id', 'plan_id'],
>             sqlBatch: {
>               thisKey: 'plan_id',
>               parentKey: 'id',
>               sqlJoin: (junctionTable, planTable) =>
>                 `${junctionTable}.item_id = ${planTable}.id`,
>             },
>           },
>         },
>       },
>     },
>   }),
> });
> ```
> 
> Some supplemental info:
> 
> * I do have a "twin" junction on the other GQLObject (Item) to complete the many to many relationship
> * All of the tables are setup correctly (in accordance to the metadata given to join-monster) in the Postgres DB

Same error!

**Comment by nicoabie** [comment]
I'm closing this issue until a reproducible example is provided.

For that there is a new repository https://github.com/join-monster/join-monster-sscce to make it easier.

Any feedback is welcome, thanks.
