### ISSUE TITLE
AliasNamespace generates alias names longer than allowed by PostgreSQL

### ISSUE THREAD

**Issue by spilth** [join-monster/join-monster#396]
We're having an issue on our project where the SQL generated by Join Monster eventually results in alias table names that are too long for PostgreSQL, are truncated and end up colliding and causing errors.

We changed the alias name generation logic to the following and we're seeing aliasNumbers upwards of 600. We've yet to determine why so many aliases are being generated.

```javascript
name = name.replace(/\s+/g, '').replace(/[^a-zA-Z0-9]/g, '_').slice(0, 10);

var aliasNumber = 0;
var aliasName = name;

while (this.usedTableAliases.has(aliasName)) {
  aliasNumber++;
  aliasName = name + "_jm" + aliasNumber;
}

console.log("ALIAS NUMBER: " + aliasNumber);
this.usedTableAliases.add(aliasName);

return aliasName;
```

**Comment by dennisc9** [comment]
I'm having the same issue on my end!
