### ISSUE TITLE
Connections inside of union fragments are not converted from arrays

### ISSUE THREAD

**Issue by meticoeus** [join-monster/join-monster#401]
It seems any Relay connection inside a fragment in a union or interface is ignored by the arrToConnection function since this function ignores typedChildren in the SQL AST.

Example query:
```
{
  files {
    edges {
      node {
        id
        name
        path
        
        ... on Folder {
          contents {
            edges {
              node {
                id
                name
                path
              }
            }
          }
        }
      }
    }
  }
}
```

Expected output:
```
{
  "data": {
    "files": {
      "edges": [
        {
          "node": {
            "id": "Rm9sZGVyOjE=",
            "name": "a folder",
            "path": "/",
            "contents ": {
              "edges": [
                {
                  "node": {
                    "id": "Rm9sZGVyOjI=",
                    "name": "another folder",
                    "path": "/a folder/"
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
```

Actual output:
```
{
  "data": {
    "files": {
      "edges": [
        {
          "node": {
            "id": "Rm9sZGVyOjE=",
            "name": "a folder",
            "path": "/",
            "contents ": {
              "edges": null
            }
          }
        }
      ]
    }
  }
}
```

Using debugging mode I can see that the data is retrieved correctly and initially stored as an array but the sqlAST contains the SQLASTNode information in sqlAST.typedChildren.Folder[] rather than sqlAST.children and so it never processes the array into connection format and the response edges is null instead of an array of nodes.

**Comment by hugobarreiro** [comment]
Guys, any updates about this? I'm facing the same problem right now and I'll be very thankful if it gets merged.

**Comment by alexbbt** [comment]
@hugobarreiro We need automated tests on the PR before it can be merged.

**Comment by hugobarreiro** [comment]
Does @meticoeus or some maintainer need to write them? Can't us contribute with this to get it done quickly?

**Comment by alexbbt** [comment]
You can definitely contribute these! Please do in fact

**Comment by hugobarreiro** [comment]
Done! I hope it is all right.

**Comment by meticoeus** [comment]
@hugobarreiro Thanks for tackling the unit test part of this fix. I haven't been able to spend more time on this lately.

**Comment by hugobarreiro** [comment]
Thanks @lorensr for merging and releasing the version 2.1.2. But I still cannot use the updated package. The reference at yarn still points to version 2.1.1 and, although we pointed to the git tag, it seems it's not built and, so, webpack cannot resolve it.

Can you, or maybe @alexbbt help me with this? I don't know if I am doing something wrong or what.

**Comment by lorensr** [comment]
2.1.2 hasn't been published to npm yet—we're figuring out a new process for that ☺️

**Comment by lorensr** [comment]
Published! Let us know if it works for you. Thanks for contributing!

**Comment by hugobarreiro** [comment]
@lorensr It worked! Thanks for publishing and thanks @meticoeus for the fix. It would take so much longer for me to do it.
