### ISSUE TITLE
Querying an interface with types that share extra columns in common results in aliased properties in the resolver function

### ISSUE THREAD

**Issue by meticoeus** [join-monster/join-monster#403]
I have an interface with multiple implementing types. Two of these types happen to share a property that is not in the interface. This property is calculated from the data in the same column in the table for both types so each type uses `sqlDeps `in the field data passed to join-monster. When I query the interface and use fragments to get this overlapping property (among others unique to each type) the resolver function gets back `property@type` instead of just `property`.

I'm not sure if this is expected behavior but if it is it should be documented somewhere or fixed.

Simple Example

```graphql
query {
  things: IThingConnection
  getBarById(id: ID!): Bar
}

interface IThing {
  id: ID!
  name: String!
}

type Foo implements IThing {
  id: ID!
  name: String!
}

type Bar implements IThing {
  id: ID!
  name: String!
  description: String
}

type Baz implements IThing {
  id: ID!
  name: String!
  description: String
}
```

```js
const schema = {
  Foo: {
    sqlTable: 'things_table',
    alwaysFetch: ['thing_type'],
    fields: {
      id: {
        sqlColumn: 'id'
      },
      name: {
        sqlColumn: 'name'
      },
      description: {
        sqlDeps: ['description']
      },
    }
  },
  Bar: {
    sqlTable: 'things_table',
    alwaysFetch: ['thing_type'],
    fields: {
      id: {
        sqlColumn: 'id'
      },
      name: {
        sqlColumn: 'name'
      },
      description: {
        sqlDeps: ['description']
      },
    }
  },
  Baz: {
    sqlTable: 'things_table',
    alwaysFetch: ['thing_type'],
    fields: {
      id: {
        sqlColumn: 'id'
      },
      name: {
        sqlColumn: 'name'
      },
      description: {
        sqlDeps: ['description']
      },
    }
  }
};
```

Notice that Bar and Baz share a property that is not in the interface and they they both use the same column as a sqlDeps column to fetch..

When we query the interface

```graphql
{
  things {
    edges {
      node {
        id
        name

        ... on Bar {
          description
        }

        ... on Baz {
          description
        }
      }
    }
  }
}
```

The resolver function for description gets a parent like this:

```js
parent = {
  id
  name
  description@Bar
  description@Baz
}
```

A query on getBarById results in the parent having a 'description' property in the resolver as expected.

**Comment by meticoeus** [comment]
After trying to work around this I'm convinced this needs to be considered a bug. A given object can only be one type once __typename is resolved so these extra `property@type` values need to be resolved to a single `property` somehow. The alternative is the user polluting all affected resolvers with defensive checks that the value might be `property` and it might be `property@type`, which makes sharing common resolvers for a property that multiple types use completely impractical.

**Comment by mavnn** [comment]
Agreed that this appears to be a bug. We ended up adding a pre-processing step to our resolve functions to remove the suffixes, but it isn't ideal.

**Comment by nicoabie** [comment]
Can you file a https://github.com/join-monster/join-monster-sscce ?

**Comment by nicoabie** [comment]
@kryops wondering if the work on aliases you did fixes this issue or something the `defaultFieldResolver` can take care of.

**Comment by kryops** [comment]
It sure sounds similar; I'm pretty sure my alias PR did not change anything here though.

A reproduction would be great, maybe even within the existing test suite. I was not able to reproduce this with my limited knowledge of GraphQL unions and interfaces 😕 

I tried modifying the following test in `unit.js`:

```js
test.only('it should an interface type', async t => {
  const source = `
    {
      user(id: 1) {
        writtenMaterial2 {
          __typename
          id
          body
          ... on Comment {
          authorId
            postId
            likers {
              fullName
            }
          }
          ... on Post {
            authorId
          }
        }
      }
    }
  `
  // ...
```

and added resolvers to `Comment.authorId` and `Post.authorId` like this:

```js
resolve: (source, args, context, info) => {
  console.log('resolve Post.authorId', source);
  return source[info.fieldName];
}
```

But this did not add a suffix to the `authorId` field in the resolvers:

```js
Comment resolve {
  'id#$ty': '1Comment',
  '$type': 'Comment',
  id: 1,
  body: 'Wow this is a great post, Matt.',
  authorId: 1,
  postId: 1,
  likers: [ { id: 2, first_name: 'matt', last_name: 'elder' } ]
}

Post resolve {
  'id#$ty': '2Post',
  '$type': 'Post',
  id: 2,
  body: 'Check out this cool new GraphQL library, Join Monster.',
  authorId: 1,
  likers: []
}
```

What did I do wrong? 😅

**Comment by nicoabie** [comment]
No no, this issue is 4 years old! But as it has something to do with suffixes I thought about your fix. I'll try to replicate it, thanks for your feedback!

**Comment by nicoabie** [comment]
Here there is a repro showing it works for version 3.3.4, also tested 4.0.0 and works too.
https://github.com/join-monster/join-monster-sscce/pull/4
