### ISSUE TITLE
List of values in the Args to frame WHERE CLAUSE with in condition 

### ISSUE THREAD

**Issue by divyamvpandian** [join-monster/join-monster#411]
Hello, Thanks a lot for this module and it fastened the development of GraphQL much quicker. 
I use Oracle DB. I have a schema where few objects will have arguments with type as String or List.   

Is there a way to frame the WHERE Clause with list of values in the arguments.  My resolve section is as below 

 where: (tblname, args, context) => {
     if(args.userid){
     whereClause.push(`${tblname}."userid" in :userid`);
}
  }

I tried passing arguments in query as _user(userid:"2,3")_ OR _user(userid:"(2,3)")_. It did not work, The second option, though not very nice to a enduser, i expected to work as it exactly get replaced in the Query as _user in (2,3)_. But it did not work. Can i know if i miss anything

**Comment by alexbbt** [comment]
You will need to create separate queries for 1 vs many. You can create something like `userByID(id: 1])` and `usersById(ids: [1,2,3])`. Then for the array version, add a where in clause using the ids variable.

See this answer for a similar problem
https://stackoverflow.com/a/40644530

**Comment by divyamvpandian** [comment]
Thank you , I changed argument as GraphQLList(GraphQLInt) and passed [1,2,3]. I see an Oracle error _ORA-01484 arrays can be only bound to plsql_. Will check. 

Also i do have 100+ objects each with 2 to 3 args which users may pass either a string or List. Wanted to check if i can do for a generic WHERE clause with IN

**Comment by alexbbt** [comment]
There is no built in generic `WHERE IN` but you can always create a helper function to generate the standard `WHERE IN`.
