### ISSUE TITLE
Does join-monster support sorting/filtering parents by a child connection?

### ISSUE THREAD

**Issue by prm-dan** [join-monster/join-monster#412]
Here's an example

type Parent {
  child: Child // just one child
  isActive: bool
}

type Child {
  name: string
  isActive: bool
}

Does join-monster support doing a connection query at the parent level that would let me sort/filter by Child.name or Child.isActive?

**Comment by divyamvpandian** [comment]
Would like to know if you found any workaround of doing this

**Comment by prm-dan** [comment]
I ended up implementing my own join entity through GraphQL and exposing that.

**Comment by divyamvpandian** [comment]
Sure @quietgopher
Posted similar Qn - https://github.com/join-monster/join-monster/issues/417 
I have lot of entities with its related entities and do not want to create a new type for each combination.

**Comment by nicoabie** [comment]
See https://github.com/join-monster/join-monster/issues/417#issuecomment-674895114
