### ISSUE TITLE
Enforce maximum page size

### ISSUE THREAD

**Issue by hugobarreiro** [join-monster/join-monster#416]
I have a paginated field and everything about `join-monster` looks fine, but I wish I had some sort of validation on `first` argument of my query.

I don't want my client to query for a thousand items at once, just for, let's say, a hundred. But I didn't find any kind of validation like this. Is this implemented somehow, but I didn't find it, or at roadmap in a near future? I guess it could be something like this, at field specs:
```
{
  ...
  sqlPaginate: true,
  sqlPageLimit: 100,
  ...
}
```

**Comment by barbieri** [comment]
seems code such as https://github.com/join-monster/join-monster/blob/145d92e965d4ac5b58c93570b5ed03b3d7fff222/src/stringifiers/shared.js#L150-L151 will directly access `args.first` (also for `last`), also https://github.com/join-monster/join-monster/blob/145d92e965d4ac5b58c93570b5ed03b3d7fff222/src/array-to-connection.js#L53-L55 just access it directly (or at most `parseInt()` in an inconsistent way).

It would be nice to be able to configure a pagination limit as proposed.

**Comment by vasundhara-digitalairtech** [comment]
For this implementation, which would be the preferred solution?
1. Showing an error message informing the user of max page size
2. Only returning max page size regardless of what user is querying?

**Comment by vasdhara** [comment]
For this implementation, which would be the preferred solution?

1. Showing an error message informing the user of max page size, or
2. Only returning max page size regardless of what user is querying?

**Comment by airhorns** [comment]
In my mind this would be similar to any other incorrectly provided argument to a GraphQL call like a number for a string or passing no argument where one should be required. GraphQL's convention there is to throw an error about those things as opposed to try to recover gracefully from them, so I think this too should be an error.
