### ISSUE TITLE
GraphQL Join Monster Filter Arguments in child Objects

### ISSUE THREAD

**Issue by divyamvpandian** [join-monster/join-monster#417]
Hi,
Would like to know how to apply argument filter on child objects.
For eg, I have declared model with Book and Customers as below. one Book can have many customers. In Query Root i gave args for both types. If i make a Query as(1) and (2) in the below example, it works. I want to make a Query like in (3). Should i be again adding all the possible args of customer in customer.js? 

**_Book.js_**
const Book = new GraphQLObjectType({
  name: 'Book',
  fields: () => ({
    id: {
      type: GraphQLInt
    },
    name: {
      type: GraphQLString
    },
    customers:{
		type: GraphQLList(Customer)
    }
  })
})

**_Customer.js_**
const Customer = new GraphQLObjectType({
  name: 'Customer',
  fields: () => ({
    id: {
      type: GraphQLInt
    },
    fullName: {
      description: 'A Customer\'s first and last name',
      type: GraphQLString
    }
  })
})

**_QueryRoot,js_**
 `import joinMonster from 'join-monster'

const QueryRoot = new GraphQLObjectType({
	name: 'Query',
	fields: () => ({
		book: {
			type: new GraphQLList(Book),
			args: {
				id: {
					type: new GraphQLNonNull(GraphQLInt)
				}
			},
			where: (booksTable, args, context) => {
				return `${booksTable}.id = ${args.id}`
			},
			resolve: (parent, args, context, resolveInfo) => {
				return joinMonster(resolveInfo, {}, sql => {
					return database.simpleExecute(sql, args)
				})
			}
		},
		customer: {
			type: new GraphQLList(Customer),
			args: {
				id: {
					type: new GraphQLNonNull(GraphQLInt)
				}
			},
			where: (customersTable, args, context) => {
				return `${customersTable}.id = ${args.id}`
			},
			resolve: (parent, args, context, resolveInfo) => {
				return joinMonster(resolveInfo, {}, sql => {
					return database.simpleExecute(sql, args)
				})
			}
		},
	})
})`

**Query**:
1)  {
  book(id:"20") { 
   name
    customers {
      fullName
    }
  }
}

2)  {
  customer(id:"20") { 
   fullName
  
  }
}

3)
 {
  book(id:"20") { 
   name
    customers(id:"2") {
      fullName
    }
  }
}

**Comment by airhorns** [comment]
If you want to filter the child connection in a hardcoded way, you would need to use a `where` condition on the field of the parent pointing to the child. If you want arguments passed at the top level to apply to other fields (which is kind of unexpected from a GraphQL consumer standpoint and probably means there's a better way to do it), you could pass them down to the `resolve` functions of the children by putting them in the GraphQL context.
