### ISSUE TITLE
Missing results when using batch

### ISSUE THREAD

**Issue by delaneyj** [join-monster/join-monster#424]
Using `3.0.0-alpha.2`. I'm sure this is just a lack of understanding about how batching work and unclear if its just misuse of the API.  I have a complicated set (1500+) SQL tables I have no control over and have a query similar to...

```gql
{
  node_foo {
    id
    firstName
    edge_to_bar {
      id
    }
    id
    type
  }
}
```
which does return results when using sqlJoin
```json
{
  "data": {
    "node_foo": [
      {
        "id":"A",
        "firstName": "A",
        "edge_to_bar": null
      },
      {
        "id":"B",
        "firstName": "B",
        "edge_to_bar": {
          "id": "abcd"
        }
      },
      {
        "id":"C",
        "firstName": "C",
        "edge_to_bar": {
          "id": "cdef"
        }
      }
    ]
  }
}
```
with the simplified SQL being 
```sql
SELECT
  node_foo.id,
  node_foo.firstName,
  edge_to_id.id
FROM node_foo
LEFT JOIN bar edge_to_id ON node_foo.id = edge_to_id.from_id 
```
however if I use sqlBatch the results are... lack of A 
```json
{
  "data": {
    "node_foo": [
      {
        "id":"B",
        "firstName": "B",
        "edge_to_bar": {
          "id": "abcd"
        }
      },
      {
        "id":"C",
        "firstName": "C",
        "edge_to_bar": {
          "id": "cdef"
        }
      }
    ]
  }
}
```
with SQL being 
```sql
SELECT
  id,
  firstName
FROM node_foo
SELECT
  id,
  from_id
FROM edge_to_bar
WHERE from_id IN ('A','B','C','D')
SELECT
  id,
  firstName
FROM node_foo
WHERE "node"."id" IN ('B','C','D')
```

So the odd part is the ID is in the batch, but the resulting data doesn't include the node that has a null edge.  What could I be missing to cause this?

**Comment by delaneyj** [comment]
Is this a case of sqlBatch using `JOIN` instead of `LEFT JOIN`?  How would I control that behavior?

**Comment by delaneyj** [comment]
[In the docs](https://join-monster.readthedocs.io/en/latest/batch-many-many/) I see 
```ts
 sqlBatch: {
              // the matching column in the junction table
              thisKey: 'follower_id',
              // the column to match in the user table
              parentKey: 'id',
              // how to join the related table to the junction table
              sqlJoin: (junctionTable, followeeTable) =>
                `${junctionTable}.followee_id = ${followeeTable}.id`
            }
```
But if I set my own sqlJoin inside of sqlBatch it never gets hit.

**Comment by nicoabie** [comment]
Can you file a https://github.com/join-monster/join-monster-sscce ?

**Comment by delaneyj** [comment]
I asked about this 4 years ago, I've unfortunately long abandoned this approach

**Comment by nicoabie** [comment]
Yes, sorry to hear that. I just started as a maintainer precisely because of that lack of activity.
