### ISSUE TITLE
sqlPaginate always adds total aggregation even if it's not even used

### ISSUE THREAD

**Issue by EloB** [join-monster/join-monster#426]
I'm not sure if I do something wrong but my queries always include "$total" (when `sqlPaginate: true` see below) even if I don't use either `total` or in my case `totalCount` or `pageInfo` in my graphql query. It would be amazing if it was only included when needed.
 
`SELECT "mytable".*, count(*) OVER () AS "$total"`

Is this intended?

**Comment by nicoabie** [comment]
Can you file a https://github.com/join-monster/join-monster-sscce ?

**Comment by nicoabie** [comment]
https://join-monster.readthedocs.io/en/latest/pagination/ offset pagination needs to calculate the total
