### ISSUE TITLE
Link to demo does not work

### ISSUE THREAD

**Issue by unlight** [join-monster/join-monster#431]
Link to demo
[basic](http://join-monster.herokuapp.com/graphql?query=%7B%0A%20%20user(id%3A%202)%20%7B%0A%20%20%20%20fullName%0A%20%20%20%20email%0A%20%20%20%20posts%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20body%0A%20%20%20%20%20%20createdAt%0A%20%20%20%20%20%20comments%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20body%0A%20%20%20%20%20%20%20%20author%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20fullName%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

```
There's nothing here, yet.
```

**Comment by lorensr** [comment]
Thanks for reporting. We no longer have access to that Heroku account, so we need to create a new one and update the link.

**Comment by luke-john** [comment]
Just a note that the demo source code which is also linked throughout the docs is also missing.

https://github.com/stems/join-monster-demo

**Comment by janto** [comment]
Any progress on at least a working link to a demo from the docs and example dir? it is 404 at the moment and I don't see any existing code.

**Comment by captainmike** [comment]
Any example app one can link to would be appreciated!

**Comment by why-el** [comment]
The link is still broken as of today, three years later. I suggest you remove it from the main README at least.
