### ISSUE TITLE
Fails if I extend GraphQLObjectType

### ISSUE THREAD

**Issue by Wyctus** [join-monster/join-monster#442]
### Description

If I create a GraphQL type the following way, then everything works as expected:

```typescript
const Author: GraphQLObjectType = new GraphQLObjectType({
        name: 'Author',
        extensions: {
            joinMonster: {
                sqlTable: 'authors',
                uniqueKey: 'id',
            }
        },
        fields: () => ({
            id: {
                type: GraphQLInt
            },
            user: {
                type: GraphQLInt
            },
            name: {
                type: GraphQLString
            },
            profile_photo: {
                type: GraphQLInt
            },
            description: {
                type: GraphQLString
            }
        })
});
```

But for some specific reason, I have to extend the `GraphQLObjectType` type to abstact away a couple of things:

```typescript
class Model extends GraphQLObjectType {
    constructor() {
        super({
            name: 'Author',
            extensions: {
                joinMonster: {
                    sqlTable: 'authors',
                    uniqueKey: 'id',
                }
            },
            fields: () => ({
                id: {
                    type: GraphQLInt
                },
                user: {
                    type: GraphQLInt
                },
                name: {
                    type: GraphQLString
                },
                profile_photo: {
                    type: GraphQLInt
                },
                description: {
                    type: GraphQLString,
                }
            })
        });
    }
}
```

Now if I use the new `Model` class instead of the `GraphQLObjectType` then `join-monster` fails, since it relies on the `constructor.name` to recognize tables, as you can see [here](https://github.com/stems/join-monster/blob/cfa3537fd3e2f10f57bab2e75a85322acae5590c/src/query-ast-to-sql-ast/index.js#L152).
But in my case, due to extending the class, `constructor.name` becomes `Model`, so it wont recognize it as `GraphQLObjectType` anymore.

A possible solution is to check if the parent is a `GraphQLObjectType` by something like: `Object.getPrototypeOf(instance.constructor) === GraphQLObjectType`. 
(But this should be done recursively, to support multilevel inheritance.)

Is there any workaround which can help in my usecase? 

### Environment

- **Version of this library used:** 3.0.1

**Comment by nicoabie** [comment]
Can you file a https://github.com/join-monster/join-monster-sscce ?

**Comment by nicoabie** [comment]
You can do it like this https://github.com/graphql/graphql-js/discussions/3266
