### ISSUE TITLE
Filter Queries

### ISSUE THREAD

**Issue by josercarmo** [join-monster/join-monster#62]
So, i would like to suggest an idea. Join-monster is aweosome! The way graphqlcool implemented filters was very good, and here would be wonderful.

[https://www.graph.cool/docs/tutorials/designing-powerful-apis-with-graphql-query-parameters-aing7uech3](https://www.graph.cool/docs/tutorials/designing-powerful-apis-with-graphql-query-parameters-aing7uech3)

**Comment by theobat** [comment]
I feel like you can already do that by using the where function and the args passed inside your graphql query, although it seems you don't have the names of all the tables involved in your query yet...

**Comment by acarl005** [comment]
Their API is very nice. Appealing as it is, I don't think it should be built into Join Monster. @theobat is correct that this can be built within the existing capabilites of Join Monster. The `where` function now has access to all the aliases of the tables from the parent GraphQL types. If someone wants to write a module that can convert the graphcool arguments to a where function, I'd happily link to it in the README.
