### ISSUE TITLE
How can I execute deep where condition?

### ISSUE THREAD

**Issue by itaied246** [join-monster/join-monster#63]
I have a model `Offer` related to `Game`.
I expose a query for `offers`, and I want to filter the results using a field from `Game` (let's say `platform`).
How can I manage to do it?

From the docs all I could find is to use the `where` condition on the `Offer` table, 
how can I pass on the where condition to the `Game` table?

`Offer` object:

````
const OfferType = new GraphQLObjectType({
  name: 'Offer',
  sqlTable: 'Offer',
  uniqueKey: 'id',
  description: 'This object represents the offers for the specified user.',
  fields: () => ({
    id: {
      description: 'The id of the offer.',
      type: GraphQLInt,
    },
    game: {
      description: 'The corresponding game of the offer.',
      type: GameType,
      sqlJoin: (thisTable, joinWith) => `${thisTable}.gameId = ${joinWith}.id`,
    },
  }),
});
````

`Game` object:

````
const GameType = new GraphQLObjectType({
  name: 'Game',
  sqlTable: 'Game',
  uniqueKey: ['name', 'platform'],
  fields: () => ({
    id: {
      description: 'The ID of the game.',
      type: GraphQLInt,
    },
    platform: {
      type: PlatformType,
      description: 'The corresponding platform for this game.',
    },
  }),
});
````

`offers` query:

````
const offers = {
  type: new GraphQLList(OfferType),
  args: {
    id: {
      type: GraphQLInt,
    },
    platform: {
      type: PlatformType,
      description: 'Query offers for the specified platform.',
    },
  },
  resolve: (_, args, context, resolveInfo) =>
    context.select(resolveInfo, args),
};
````

**Comment by acarl005** [comment]
@itaied246 
Can you fulfill your use case by adding another expression to the `JOIN` condition?
```js
game: {
      description: 'The corresponding game of the offer.',
      type: GameType,
      sqlJoin: (thisTable, joinWith) => `${thisTable}.gameId = ${joinWith}.id AND ${joinWith}.platform = ${...}`,
    },
```

**Comment by acarl005** [comment]
It seems the `where` function would benefit from receiving it's parent table alias. Ideally it could know all the table aliases, but it would be challenging to specify which one you want to refer to. Maybe the programmer needs to be able to specifically choose their table aliases on each `JOIN`.

**Comment by itaied246** [comment]
Hi @acarl005 ,
It doesn't make much sense to join the tables based on queries the API may offer.
As I see it, the whole point of `join-monster` is to abstract the way queries are executed in a very efficient way. If I need to build the join logic according to the API layer, then I miss the point of abstraction.

Nobody of `join-monster` users tried to query data according to related tables?
It is a very common query in SQL, how can we make it?

**Comment by acarl005** [comment]
@itaied246 I believe your use case is now possible in **v0.9.8**. The `where` function has a new fourth parameter which contains its parent tables' aliases [[docs](http://join-monster.readthedocs.io/en/latest/where/#referencing-related-tables)]. So you should be able to do something like this:
```js
const OfferType = new GraphQLObjectType({
  name: 'Offer',
  sqlTable: 'Offer',
  uniqueKey: 'id',
  description: 'This object represents the offers for the specified user.',
  fields: () => ({
    id: {
      description: 'The id of the offer.',
      type: GraphQLInt,
    },
    game: {
      description: 'The corresponding game of the offer.',
      type: GameType,
      where: (gameTable, args, ctx, parents) => `${gameTable}.platform = ${/* do something with parents[0] the offer table alias*/}`,
      sqlJoin: (thisTable, joinWith) => `${thisTable}.gameId = ${joinWith}.id`,
    },
  }),
});
```
Let me know if this works.

Having said that, I want to make some remarks about Join Monster's abstraction level. The point isn't to *abstract away* the SQL query that's generated. We want to embrace it. Be fully aware of the queries so you can do things like choose database indexes judiciously. The point of Join Monster is to provide a framework around the `graphql-js` implementation that constructs that one SQL query dynamically based on the GraphQL query. This very time consuming to write yourself and it requires a lot of knowledge of the `graphql-js` internals. Join Monster is meant to spare the developer this burden, not alleviate them of knowing how to write SQL queries.

Some users, ourselves included, *have* altered their `JOIN` logic based on GraphQL arguments. I would even argue the `JOIN` conditions are semantically very similar to `WHERE` conditions. You can achieve joins using where clauses instead.
```sql
SELECT user, post
WHERE user.id = post.author_id AND
  user.first_name = 'Andy';
```
So if it makes sense to alter the `WHERE` condition based on the GraphQL API, I don't think it's nonsensical to alter the `JOIN` condition based on the GraphQL API. It's a subjective thing. But now you may not have to! The `where` function has access to more tables now.

**Comment by itaied246** [comment]
@acarl005  Thanks you very much for the help!
I will try it soon and post in a few days what I did and how it works.

**Comment by asrytis** [comment]
@itaied246 did you ever find solution for this?

**Comment by upasanadash** [comment]
> ```js
>  where: (gameTable, args, ctx, parents) 
>in parents it is taking the same table. not parent table. Could you please tell me how to do this. I want to add some condition based on the parent table.

**Comment by upasanadash** [comment]
@acarl005 please check and tell me the solution
