### ISSUE TITLE
Promises and args in sqlJoin function

### ISSUE THREAD

**Issue by maxpain** [join-monster/join-monster#67]
Please make passing args and ability to return promises in sqlJoin function.

**Comment by acarl005** [comment]
@Maxpain177 The GraphQL args were exposed as the third parameter in the `sqlJoin` function in **v0.9.4** [[docs](http://join-monster.readthedocs.io/en/latest/start-joins/#writing-the-join-condition)]. I'll add promise support very soon!

**Comment by maxpain** [comment]
@acarl005 Oops, sorry. Then, please add `context` :D

**Comment by acarl005** [comment]
In **v0.9.9** the `sqlJoin` function receives the context as the 4th parameter [[docs](http://join-monster.readthedocs.io/en/latest/API/#sqlJoin)]. It can also return a promise, so async `sqlJoin` functions are supported.

**Comment by maxpain** [comment]
Thanks!
