### ISSUE TITLE
looped\recursive query not working correctly

### ISSUE THREAD

**Issue by LiorArbel** [join-monster/join-monster#75]
Hey guys, thanks for the hard work!

Say I have a simple schema for a forum which looks roughly like you would expect:

    User {
        nickname: String
        threads: [Thread]
    }

    Thread {
        title: String
        text: String
        comments: [Comment]
        creator: User
    }

    Comment {
        commenter: User
        text: String
    }

And say I want to show in my ui a specific **thread** with all its **comments,** for every **comment** to show the **commenter,** BUT! for every **commenter**, to show all his last **threads** when the user hovers over his name for example.

If I got graphql right, my query will look like this:

    Thread(title: 'bla bla'){
        title,
        text,
        comments {
            text,
            commenter {
                nickname,
                threads {
                    title
                }
            }
        }
    }

(If this is a graphql anti-pattern please stop me here and I'll be really happy if you could describe why or link me with a solution)

When I tried to send a query like that to my join monster code, the problem was very simple - 

Join monster adds `WHERE title = 'bla bla'` to the end of our sql query since we queried `Thread(title:'bla bla')`, so it won't return the **threads of the commenters** whos titles are different than 'bla bla'. 

(even this is not exact since its not about the `where` clause its more about the join, which is now only on the threads we've filtered... I don't understand it well enough to even explain how this could be solved :) )

How can I solve this problem??

**Comment by acarl005** [comment]
You should add the table alias before the column name in your WHERE clause. The where function has the table alias that gets generated as its first parameter. So it should look something like this...

```js
// on the top-level thread field
name: 'QueryRoot',
fields: () => ({
  thread: {
    type: Thread
    args: {...},
    // ...
    // this should make sure only the top level thread table is filtered on
    where: (threadTable, args) => `${threadTable}.title = ${args.title}`
  }
})
```

Join Monster will make sure to automatically generate unique table aliases for the thread table in the root-level and in the deeper level below "commenter". So utilizing that table alias can allow you to filter only on the top-level.

**Comment by LiorArbel** [comment]
I'm really sorry, turns out my real problem was with my tables, I tried to use join-monster on a many-to-many relationship and this example was not good to show my problem.

I managed to solve it, but thank you anyway!
