### ISSUE TITLE
support oracle

### ISSUE THREAD

**Issue by sibelius** [join-monster/join-monster#78]
oracle pagination is a little bit different

this is an example: https://github.com/oracle/node-oracledb/blob/master/examples/rowlimit.js#L64

**Comment by acarl005** [comment]
I've been playing around with Oracle. It looks like version 12c is needed to support pagination, as LATERAL and OFFSET are not available in version 11g. Version 12c does not seem to have a free express edition, so my access to Oracle is limited as of right now. If I can get a version of 12c to develop against, I can add it in pretty easily.

**Comment by praseedasathaye** [comment]
I can help you with this. Please let me know how we can forward with this?

**Comment by acarl005** [comment]
I am currently working on this. I'm blocked by [this stackoverflow question](http://stackoverflow.com/questions/42593148/inconsistent-behavior-with-cross-apply-and-outer-apply) I posted if someone would like to help me debug.

**Comment by acarl005** [comment]
Oracle is now a supported dialect in `v1.1.0-beta.1` complete with pagination. Expect an un-handled edge case or two, as its a new addition to the beta version.

```js
{
  //...
  resolve: (parent, args, ctx, info) => {
    return joinMonster(info, {}, sql => {
      // talk to your oracle server
    }, { dialect: 'oracle' })
  }
}
```

You may now select `'oracle'` in the `dialect` option for `joinMonster`.

**Comment by sibelius** [comment]
Tks for the great work

**Comment by praseedasathaye** [comment]
Thank You.
