### ISSUE TITLE
Where condition get table joined name

### ISSUE THREAD

**Issue by thifranc** [join-monster/join-monster#87]
Hi !
I'm trying to add a where condition on a query, but I can't get my table name : 
```
const ProductLang = new ObjectType({
  name: 'ProductLang',
  sqlTable: 'product_lang',
  uniqueKey: 'id',
  fields: {
    id: { type: new NonNull(ID) },
    product_id: { type: new NonNull(ID) },
    lang: {
      type: Lang,
      sqlJoin(productLangTable, langTable) {
        return `${langTable}.id = ${productLangTable}.lang_id`
      }
    },
    description: { type: StringType },
  },
});
```
```
const products = {
  type: new List(ProductLang),
  description: 'Return products',
  args: {
    lang: {
      type: StringType,
      defaultValue: 1
    }
  },
  where: (productTable, args, context) => {
    console.log('I would love to see langTable name',  productTable);
    //here I can log "products" but I want to get "lang" also
  }
```
How can I get my joined table name in the where condition ?
Ideally, my query should look like :
```
SELECT * FROM product_lang JOIN lang ON (product_lang.lang_id=lang.id) WHERE lang.name='fr'
```
Do you have any idea of how to get this name ?

**Comment by acarl005** [comment]
@thifranc 
You can use the fourth parameter of the `where` function. [[docs](http://join-monster.readthedocs.io/en/latest/API/#where)]. It has an array of the related table names from the parent GraphQL fields.

Or, you could put that expression in the `JOIN` condition like this...
```js
{
    lang: {
      type: Lang,
      sqlJoin(productLangTable, langTable) {
        return `${langTable}.id = ${productLangTable}.lang_id AND ${langTable}.name = 'fr'`
      }
    },
}
```

**Comment by thifranc** [comment]
Hi !
I've tried both and none worked : 
I can't get anything from the fourth arg of the where function my console.log gives me an empty array.

And though I can modify my sqlJoin as you suggested, as join-monster do a LEFT JOIN, I get this : 
```
SELECT "products"."id" AS "id", "products"."description" AS "description", "lang"."id" AS "lang__id", "lang"."name" AS "lang__name" FROM product_lang AS "products" LEFT JOIN lang AS "lang" ON "lang".id = "products".lang_id AND "lang".name = 'fr';
```
```
 id |   description    | lang__id | lang__name
----+------------------+----------+------------
  1 | je suis thibault |        1 | fr
  2 | i am batman      |          |
```
And I'm back with the same issue having to separate those rows with something like : 
```
WHERE lang.name IS NOT NULL
```
to add in the where function whereas I can't get the table joined name (lang), and that's what was bothering me in the first place.

I have not seen the possibility to specify the JOIN to be an INNER one in the docs, and I can't understand why I'm not getting anything else of an empty array in the fourth arg of my where function, do you have any idea ?

**Comment by acarl005** [comment]
@thifranc Oh I see. The `where` function is on the level of the `ProductLang`. You need the `WHERE` condition to filter based on a value in the `Lang`, which is a child field, so it's table alias is not available to the `where` function. If you moved the `where` function down to the `Lang` level, then you wouldn't have access to the arguments. Perhaps the `where` function should give you access to all the parents args as well.

In the mean time, perhaps this is a suitable workaround?

```js
where: (productTable, args, context) => {
    console.log('I would love to see langTable name',  productTable);
    //here I can log "products" but I want to get "lang" also
    return pgEscape(`${productTable}.lang_id = (SELECT id FROM lang WHERE lang.name = %L)`, args.lang)
  }
```

Its a little hacky. I don't know which DBMS you're using but if its postgres you can use the `pg-escape` module to scrub the input. If its another one then there are similar options.

**Comment by thifranc** [comment]
Yes I'm using postgres and that's what I did before opening this issue, I'll keep it like that, it's just that I didn't want my table name to be hardcoded :) but I'll keep going like this.

Cheers and thanks a lot !
