### ISSUE TITLE
How you make these cool sql diagrams ?

### ISSUE THREAD

**Issue by collegeimprovements** [join-monster/join-monster#9]
This project is cool but your diagrams are even cooler. 
How you make them? Which tools are you using?

**Comment by acarl005** [comment]
Hey thanks! The simpler ones were made on a web app [draw.io](https://www.draw.io/) which is just a general drawing tool. They have some specific tools for schemas too.

The fancier one is a Java library called [SchemaSpy](http://schemaspy.sourceforge.net/). This one you can just point at a SQL database and it automatically inspects the tables and generates the diagrams.

**Comment by dreamcodez** [comment]
closing this ;)
