### ISSUE TITLE
Migration from Sequelize

### ISSUE THREAD

**Issue by DaVinciLord** [join-monster/join-monster#95]
Hi, I've just discovered this package and I think it's awesome.
I'm using Sequelize as an ORM but I'd like to use join-monster for querying my database. How would I migrate from Sequelize to use join-monster ? Also, what to do with my already created resolvers for creating/updating/deleting ? Can I use them with join-monster ?

**Comment by acarl005** [comment]
@DaVinciLord Thanks for the kind words! Yes, Join Monster can co-exist with Sequelize. As long as you know the columns and keys in your relations, you can set up Join Monster just as if you had created the tables with raw SQL. It doesn't matter how the tables were created. You may feel like you are repeating yourself, as you'll likely have things like column names defined in both Sequelize models *and* GraphQL object types. Join Monster does not introspect on Sequelize models.

As far as your existing resolvers, Join Monster will not prevent you from having your own custom resolvers. They will still run as always. However, they *may* become redundant if they are fetching data that `joinMonster` already knows how to fetch and it was called on a parent field. Just keep that in mind.

**Comment by josercarmo** [comment]
DaVinciLord, you can use Sequelize, Bookshelf.js, i am using knex.js in my project....its perfect with join monster. I will suggest you use join monster and sequelize.raw to run graphql query and in complex mutation graphql use the ORM.

I think you only need ORM in mutations...i think.

```javascript
             where: (userTable, args) => {
                let clause = [];
                args.name && clause.push(...[`name LIKE upper(unaccent(:name))`]);
                args.id && clause.push(...[`${userTable}.id = :id`]);
                args.cpf && clause.push(...[`id = :cpf`]);
                args.year && clause.push(...[`year = :year`]);
                whereClause.unshift(...['1=1']);
                return whereClause.join(" AND ");
            },
            resolve: (parent, args, context, ast) => {
                return joinMonster(ast, context, sql => {
                   return knex.raw(sql, args); 
               });
            }
 ```
