### ISSUE TITLE
Limit & Offset is not applied on complete join query

### ISSUE THREAD

**Issue by puttappa-raghavendra** [join-monster/join-monster#96]
Hi Team,
     Started exploring join monster for one of our project. It's very easy and pretty happy with the performance too!! 

We are facing some challenges in applying limit & offset. Need your help!!

We have a GraphQL Query as below: 

```
 {
  orders(first: 10){
    edges {
      node {
        id
        name
        order_items( filter: "{ \"type\": { \"$in\": [ \"PC\"]}}" ) {
          name
          id
        }
      }
    }
  }
}

```
In above GraphQL Query, **order_items:  filter** is in json format which is converted to SQL and used in where condition of order_lines.

SQL Generated As Below:

```
SELECT
  "orders"."id" AS "id",
  "orders"."$total" AS "$total",
  "orders"."name" AS "name", 
  "order_items"."id" AS "order_items__id",
  "order_items"."name" AS "order_items__name"
FROM (
  SELECT *, count(*) OVER () AS "$total"
  FROM eds.orders
  WHERE TRUE
  ORDER BY "id" DESC
  LIMIT 11 OFFSET 0
) "orders"
LEFT JOIN sh.order_items "order_items" ON "orders".id = "order_items".order_id
WHERE type in ( 'PC' )
ORDER BY "orders"."id" DESC
```

In above generated SQL query from join monster, first we are applying order by, limit & offset on orders table and then we are applying left join on the second table i.e order_items and condition.
 
We want to apply limit, order by on both orders and order_items table.
Please let us know how to achieve that or any other alternate way.

**Comment by acarl005** [comment]
@puttappa-raghavendra You can add pagination to both `order` and `order_lines`, (and you can nest your pagination arbitrarily deep). All you have to do is make `order_lines` a `Connection` type and set `sqlPaginate` and `orderBy` just as you've done for the `order` field.
