### ISSUE TITLE
Custom resolving of child object that maps to SQL table

### ISSUE THREAD

**Issue by tonyxiao** [join-monster/join-monster#98]
I'm getting the following error
```
If an Object type maps to a SQL table and has a child which is 
another Object type that also maps to a SQL table, you must define \"sqlJoin\", \"sqlBatch\", or \"junctionTable\" 
on that field to tell joinMonster how to fetch it. Check the \"otherUser\" field on the \"Relationship\" type.
```
However in this case my intention is to define a completely custom resolver for the child, despite the fact that it is another object type which also maps to a SQL table. Is that possible?

Basically I'd like to get joinMonster to ignore a specific field and let me resolve it myself.

**Comment by dreamcodez** [comment]
try this in your type definition:
```js
{
  // this will create a hole where id will still be used to create the spine.
  where: () => 'FALSE',
}
```

**Comment by tonyxiao** [comment]
Hmm doesn't seem to work. 

```
{
  Relationship: {
    sqlTable: 'relationships',
    uniqueKey: 'id',
    fields: {
      otherUser: {
        where: () => 'FALSE',
        resolve: () => ({ id: 222 })
      }
    }
  }
}
```

**Comment by tonyxiao** [comment]
This is what type looks like. 
```
type Relationship {
  id: Int
  state: String
  otherUser: User
}
```

**Comment by dreamcodez** [comment]
@tonyxiao for fields you can just define the resolver yourself -- as long as sqlColumn isn't defined on the field -- it won't attempt to fetch that column. Remove the where.

**Comment by dreamcodez** [comment]
@tonyxiao I see whats happening -- I stared at your code a little bit longer. Let me see if I can find a way to bypass the assumption join monster is making here in your use case.

**Comment by dreamcodez** [comment]
@tonyxiao I talked to @acarl005 and basically we need to put an explicit noop command in for these types of situations; until we can put this in a release I recommend just commenting out this line in your node_modules for now:

https://github.com/stems/join-monster/blob/ec920cdcb69b6c79a72ff3325b712ca1810f1244/src/query-ast-to-sql-ast/index.js#L97

**Comment by tonyxiao** [comment]
@dreamcodez That works for scalar fields, but not for object fields.

**Comment by tonyxiao** [comment]
Works for scalars
https://github.com/stems/join-monster/blob/ec920cdcb69b6c79a72ff3325b712ca1810f1244/src/query-ast-to-sql-ast/index.js#L107

Does not work for objects
https://github.com/stems/join-monster/blob/ec920cdcb69b6c79a72ff3325b712ca1810f1244/src/query-ast-to-sql-ast/index.js#L95

**Comment by acarl005** [comment]
@tonyxiao Yeah this seems like it will be a common use case. Just because as ObjectType is tagged with sqlTable does not necessarily mean it should be handled by JM in all fields in the schema. We need an option to opt-out. I'll think about the best way to add this in for the next release.

For now, you can fork and monkey-patch it in. You can add a property like so
```js
{
  Relationship: {
    sqlTable: 'relationships',
    uniqueKey: 'id',
    fields: {
      otherUser: {
        // tell joinMonster this is a no-op
        jmIgnore: true,
        resolve: () => ({ id: 222 })
      }
    }
  }
}
```

And then you can open `query-ast-to-sql-ast/index.js` and go to line 53 and add the following block.

```js
  if (field.jmIgnore) {
    sqlASTNode.type = 'noop'
    return
  }
```

This will tell joinMonster's AST to not compile any SQL for that branch of the schema.

Keep in mind that the code in the `src/` directory is compiled by babel so changes to the code need to eventually be built and propagated to `dist/`.

**Comment by tonyxiao** [comment]
@acarl005 actually it's still useful to be able to specify stuff like `sqlDeps`. The columns here can actually be important for resolutions of custom objects.
```
{
    sqlTable: 'relationships',
    uniqueKey: 'id',
    fields: {
      otherUser: {
        sqlDeps: [ 'user_id', 'target_id' ],
      }
    }
  }
```

**Comment by acarl005** [comment]
Hm. I'm a little bit confused. You say you want a "completely custom resolver for the child." I assume that means you want to hit the network on your own. By "completely custom," are you saying you'll be writing your own SQL query? If so, `joinMonster` won't be querying that table at that level in the schema so specifying `sqlDeps` can't really be done. You will have to inspect the `resolveInfo` on your own and execute your own logic for whether or not to include certain columns in your custom query.

On the other hand, maybe thats not what you mean. Maybe you still want Join Monster to join on the user table again and get the data, and then run a `resolve` function on the data it brings back. If thats the case, its already possible. Even if `joinMonster` fetches a field for you, it won't cause any resolver to be *ignored*. It just allows you to omit it in many cases.

**Comment by tonyxiao** [comment]
@acarl005 in addition to having join-monster complete ignore an object field (which should totally be an option), what I meant to say is that it's also useful to have computed object fields, not just computed scalar fields, that have depend on other fields. (Think the fullname example). 

In my particular case, I want to retrieve `otherUser` object based on the values of `user_id` and `target_id` columns, and I want to make sure those values are available on the `parent` argument in the resolver.

**Comment by acarl005** [comment]
Ah okay now I understand. You do want to write your own resolver, but that resolver still needs access to columns from the parent object. Yes, I agree, this is an important capability! I'll get this into the next release. Or I'll happily accept a PR if its more urgent.

**Comment by tonyxiao** [comment]
Correct! Will try my best to submit a PR next week. By the way (let me know if this is better as a separate issue), will join monster batch across multiple calls in the same request? Here's an example

```graphql
type User {
  pictures: [Picture]
}
type Picture {
  url: String
}
type RootQuery {
  searchUsers(term: String): [User]
}
```

```javascript
// via graphql-tools
const RootQuery = {
  searchForUsers: () => [...] // Do something to retrieve list of matching user ids from outside of SQL
}
const User = {
  sqlTable: 'users'
  fields: {
    picture: {
      sqlJoin(userTable, picturesTable) {
        return `${userTable}.id = ${picturesTable}.user_id`
      },
      resolver(parent, args, context, resolveInfo) {
        return joinMonster(resolveInfo, {}, sql => {
          return knex.raw(sql)
        })
      }
    }
  }
}
const Picture: {
  sqlTable: 'pictures'
}
```

and I make the following graphql query
```graphql
{
  searchUsers(term: "hello") {
    picture {
      url
    }
  }
}
```

Is it possible for joinMonster to batch the requests like the following instead of one request per user?

```sql
select url from pictures
inner join users
on pictures.user_id = users.id
where users.id IN ($idsRetrievedFromSearch)
```

**Comment by acarl005** [comment]
Yes, you can do this with `sqlBatch`. [Here](http://join-monster.readthedocs.io/en/latest/query-planning/) is the section on this in the documentation.

**Comment by acarl005** [comment]
Newest version includes two new field options: `jmIgnoreAll` and `jmIgnoreTable`. `jmIgnoreAll` will ignore all the join monster properties. `jmIgnoreTable` will ignore only the `sqlTable` tag on the object type, allowing you to specify `sqlDeps` instead.

This isn't in the documentation yet but I'll update that soon.
